import {KeysOfUnion} from "@/app/types/utils";

const JOB_FUNCTION = {
    D19: 'Academic Executive',
    L01: 'Accounting',
    D13: 'Accounting Executive',
    L48: 'Administration',
    L65: 'Agriculture / Natural Resources',
    D11: 'Analytics Executive',
    D28: 'Artificial Intelligence (AI) Executive',
    T47: 'Artificial Intelligence (AI) Technology Professions',
    C21: 'Board or Director',
    L02: 'Business Operations Management',
    L29: 'Business Process Owner',
    T03: 'Business, Data and Systems Analysis',
    C19: 'Chief Academic Officer',
    C13: 'Chief Accounting Officer - CAO',
    C11: 'Chief Analytics Officer - CAO',
    C28: 'Chief Artificial Intelligence (AI) Officer - CAIO',
    C20: 'Chief Compliance Officer - CCO',
    C27: 'Chief Customer Officer - CCustO',
    C17: 'Chief Data Officer - CDataO',
    C25: 'Chief Digital Officer',
    C01: 'Chief Executive Officer - CEO',
    C05: 'Chief Financial Officer - CFO',
    C12: 'Chief Human Resource Officer  / SVP Talent & Learning - CHRO',
    C02: 'Chief Information Officer - CIO',
    C06: 'Chief Marketing Officer - CMO',
    L38: 'Chief Medical Officer (non-governmental role)',
    C04: 'Chief Operating Officer - COO',
    C08: 'Chief Procurement Officer - CPO',
    C14: 'Chief Risk Officer - CRO',
    C10: 'Chief Sales Officer - CSalesO',
    C09: 'Chief Security Officer - CISO',
    C07: 'Chief Strategy Officer',
    C18: 'Chief Supply Chain Officer - CSCO',
    C26: 'Chief Sustainability Officer - CSO',
    C03: 'Chief Technology Officer - CTO',
    L44: 'Compliance and Data Governance',
    D20: 'Compliance Executive',
    L42: 'Compliance Management',
    T42: 'Consultant',
    T46: 'Content and Documentation Writer',
    L39: 'Content Manager',
    C15: 'Controller',
    L46: 'Corporate Real Estate',
    D27: 'Customer Executive',
    L04: 'Customer Service',
    T07: 'Data Administration',
    T45: 'Data Architect',
    D17: 'Data Executive',
    L43: 'Data Scientist',
    T44: 'Dev Ops',
    T33: 'Developer',
    L19: 'Development and Clinical Trials',
    L13: 'Development for Internet of Things (IoT)',
    C22: 'Development Manager',
    D25: 'Digital Executive',
    L72: 'Digital Strategist',
    L28: 'Education Administration',
    D01: 'Executive',
    L24: 'Federal Government',
    L05: 'Finance and Accounting Management',
    D05: 'Financial Executive',
    L64: 'Financial Markets Risk Manager / Analyst',
    L06: 'Financial Planning and Analysis',
    L27: 'Freight Operator',
    L70: 'Health Administration',
    L40: 'Health and Safety Management',
    L67: 'Health and Social Services / Social Programs',
    D12: 'HR Executive',
    L30: 'Human Resources (Resource Development and Management)',
    L47: 'Insurance',
    ZI: 'Invalid Job Title',
    L62: 'Investment Advisor / Manager',
    T04: 'IT / Technical Management',
    D02: 'IT Executive',
    T38: 'IT Management',
    T06: 'IT Support',
    L49: 'Lawyer / Legal Profession',
    C24: 'Line of Business Executive',
    L23: 'Management Consultancy',
    L07: 'Manufacturing',
    L08: 'Marketing Communications',
    D06: 'Marketing Executive',
    L16: 'Marketing Operations',
    L41: 'Medical Research',
    C23: 'Network Operations VP',
    T28: 'Network Specialist',
    T15: 'Operations and System Administration',
    D04: 'Operations Executive',
    T41: 'Other IT',
    L69: 'Physician',
    L10: 'Plant and Facilities Management',
    L71: 'Privacy Specialist',
    T16: 'Procurement and Controls',
    D08: 'Procurement Executive',
    L11: 'Product / Service Maintenance',
    L12: 'Product Design and Development',
    T20: 'Project Manager',
    L68: 'Public Safety / Defense / Police',
    T26: 'Quality Assurance',
    L59: 'Risk Analyst / Actuarial',
    D14: 'Risk Executive',
    L03: 'Risk Management',
    L17: 'Sales',
    D10: 'Sales Executive',
    L18: 'Sales Operations',
    D09: 'Security Executive',
    T22: 'Security Management',
    L45: 'Social Media Specialist',
    T24: 'Solution and Software Architecture',
    L25: 'State or Local Government',
    L51: 'Store Operations',
    L20: 'Strategic Planning',
    T08: 'Strategy and Enterprise Architect',
    D07: 'Strategy Executive',
    T34: 'Student',
    D18: 'Supply Chain Executive',
    L14: 'Supply Chain Management',
    D26: 'Sustainability Executive',
    L73: 'Sustainability Manager',
    L15: 'Systems Engineering / Industrial',
    L66: 'Tax and Revenue',
    L52: 'Teaching Professions',
    D03: 'Technology Executive',
    L21: 'Transportation Operations and Planning',
    C16: 'Treasurer',
    D16: 'Treasury Executive',
    ZA: 'Unclassified Job Role',
    L22: 'Urban Planning / Transportation Engineering',
    T27: 'User Experience and Interface Design (UX/UI)',
}

const INDUSTRY = {
    V: 'Aerospace & Defense',
    J: 'Automotive',
    F: 'Banking',
    P: 'Chemicals & Petroleum',
    B: 'Computer Services',
    D: 'Consumer Products',
    E: 'Education',
    L: 'Electronics',
    U: 'Energy & Utilities',
    Z: 'Exclusions',
    S: 'Financial Markets',
    Y: 'Government, Central/Federal',
    G: 'Government, State/Provincial/Local',
    H: 'Healthcare',
    M: 'Industrial Products',
    N: 'Insurance',
    X: 'Life Sciences',
    K: 'Media & Entertainment',
    C: 'Professional Services',
    R: 'Retail',
    A: 'Telecommunications',
    T: 'Travel & Transportation',
    W: 'Wholesale Distribution & Services',
}

const SUB_INDUSTRY = {
    V: {
        V9: 'HQ Allocation for Aerospace & Defense and Industrial Products',
        VA: 'Aerospace',
        VB: 'Defense',
        VC: 'Ship Building',
        VW: 'Aerospace & Defense NetGen',
    },
    J: {
        J9: 'HQ Allocation for Automotive',
        JA: 'Automotive OEMs (Manuf. of Cars, Light Trucks, Motorbikes)',
        JB: 'Automotive Suppliers',
        JC: 'Heavy Equipment',
        JD: 'Distributors, Importers, Retailers',
        JW: 'Automotive NetGen',
    },
    F: {
        F9: 'HQ Allocation for Banks',
        FA: 'Banking - Other',
        FD: 'Banking - Focus 65',
        FF: 'Banking - Global Customer Management',
        FW: 'Banking NetGen',
    },
    P: {
        P9: 'HQ Allocation for Chemicals & Petroleum',
        PC: 'Chemicals & Life Sciences',
        PO: 'Petroleum',
        PW: 'Chemicals & Petroleum NetGen',
    },
    B: {
        B9: 'HQ Allocation for Computer Services and Professional Services',
        BB: 'Outsourcing',
        BC: 'Prepackaged Software',
        BD: 'System Integration',
        BE: 'DP Education',
        BG: 'Computer Maintenance & Services',
        BH: 'Business Recovery Services',
        BI: 'Computer Leasing and Rental',
        BJ: 'CSI Selected Accounts',
        BW: 'Computer Services NetGen',
    },
    D: {
        D9: 'HQ Allocation for CP and Wholesale Distribution & Services',
        DI: 'CP- Food Manufacturing',
        DJ: 'CP- Beverages & Tobacco',
        DK: 'CP- Household/Health & Beauty',
        DL: 'CP- General Processing',
        DW: 'Consumer Products NetGen',
    },
    E: {
        E9: 'HQ Allocation for Education',
        EA: 'Higher Education',
        ER: 'Basic/Secondary Education',
        EW: 'Education NetGen',
    },
    L: {
        L9: 'HQ Allocation for Electronics',
        LA: 'Electrical and Electronics',
        LB: 'Technology Systems and Microelectronics',
        LW: 'Electronics NetGen',
    },
    U: {
        U9: 'HQ Allocation for Energy & Utilities',
        UA: 'Electric',
        UB: 'Gas',
        UC: 'Combo Electric/Gas',
        UD: 'Water',
        UE: 'Waste',
        UW: 'Energy & Utilities NetGen',
        UZ: 'Electric and Gas Energy Services Traders',
    },
    Z: {
        ZA: 'Supplies Wholesalers',
        ZB: 'PC Retailer or Super Channel',
        ZC: 'M&S Parts Sales to OEM',
        ZD: 'Over the Counter Part Sales',
        ZE: 'Sales to IBM Employees',
        ZF: 'IBM Internal',
        ZG: 'Second Hand Dealers',
        ZZ: 'Unassigned Accounts',
    },
    S: {
        S9: 'HQ Allocation for Financial Markets',
        SB: 'Financial Markets - Other',
        SE: 'Financial Markets - Focus 65',
        SG: 'Financial Markets - Global Customer Management',
        SW: 'Financial Markets NetGen',
    },
    Y: {
        Y9: 'HQ Allocation for Government',
        YA: 'Finance and Administration',
        YB: 'Social Services',
        YC: 'Public Safety and Justice',
        YD: 'Environ., Transp. & Pub. Works',
        YE: 'Defense and National Security',
        YF: 'Postal',
        YG: 'Scientific',
        YW: 'Government-Central/Federal NetGen',
    },
    G: {
        GA: 'Fin. & Admin, State/Prov./Reg.',
        GB: 'Fin. & Admin, City/Municipal',
        GC: 'Fin. & Admin, County/Shire',
        GD: 'Fin. & Admin, Special District',
        GE: 'Soc. Services, State/Prov/Reg.',
        GF: 'Soc. Services, City/Municipal',
        GG: 'Soc. Services, County/Shire',
        GH: 'PS & Justice, State/Prov./Reg.',
        GJ: 'PS & Justice, City/Municipal',
        GK: 'PS & Justice, County/Shire',
        GL: 'PS & Justice, Special District',
        GM: 'Env/Trans/PubWrks, State/Prov.',
        GN: 'Env/Trans/PubWrks, City/Mun.',
        GP: 'Env/Trans/PubWrks, County/Shire',
        GR: 'Env/Trans/PubWrks, Spec. Dist.',
        GW: 'Government-State/Provincial/Reg NetGen',
        GZ: 'Other Government',
    },
    H: {
        H9: 'HQ Allocation for Health',
        HA: 'Integrated Healthcare Systems / Hospitals',
        HB: 'Physicians / Clinics',
        HC: 'Alternate Healthcare',
        HD: 'Health Plans / Payors',
        HE: 'Healthcare Other',
        HW: 'Healthcare NetGen',
    },
    M: {
        MC: 'Fabrication & Assembly',
        ME: 'Construction/Architecture/Engineering',
        MH: 'Forest Products',
        MI: 'Textiles',
        MJ: 'Metals',
        MK: 'Mining',
        ML: 'Other Process',
        MW: 'Industrial Products NetGen',
    },
    N: {
        N9: 'HQ Allocation for Insurance',
        NA: 'Insurance Carriers - Life & Asset Management (L&AM)',
        NB: 'Insurance Carriers - Property & Casualty (P&C)',
        NI: 'Insurance Intermediaries',
        NW: 'Insurance NetGen',
        NZ: 'Other Insurance, N.E.C.',
    },
    X: {
        XF: 'Pharmaceuticals',
        XW: 'Life Sciences NetGen',
    },
    K: {
        K9: 'HQ Allocation for Media & Entertainment',
        KA: 'Cable',
        KB: 'Broadcast',
        KC: 'Entertainment',
        KD: 'Printing & Publishing',
        KE: 'Sports',
        KF: 'Advertising',
        KW: 'Media & Entertainment NetGen',
        KZ: 'Associations',
    },
    C: {
        CB: 'Management Consulting',
        CC: 'Legal Services',
        CD: 'Accounting and Auditing',
        CE: 'Marketing & Public Opinion Research',
        CF: 'Business Services',
        CW: 'Professional Services NetGen',
    },
    R: {
        R9: 'HQ Allocation for Retail',
        RA: 'Retail- Apparel Manufacturing',
        RB: 'Retail- Mass Merchants',
        RC: 'Retail- Department Stores',
        RD: 'Retail- Direct Marketing',
        RE: 'Retail- Specialty',
        RF: 'Retail- Food',
        RG: 'Retail- Pharmacy/Drug',
        RH: 'Retail- Food Services',
        RR: 'Retail- Hard Goods',
        RW: 'Retail NetGen',
    },
    A: {
        A9: 'HQ Allocation for Telecommunications',
        AA: 'Wireline',
        AB: 'Wireless',
        AC: 'Broadband',
        AW: 'Telecommunications NetGen',
    },
    T: {
        T9: 'HQ Allocation for Travel & Transportation',
        TA: 'Passenger Airlines',
        TB: 'Airports',
        TC: 'Rail',
        TD: 'Urban Transportation',
        TE: 'Trucking',
        TF: 'Shipping',
        TG: 'Freight Services',
        TH: 'Travel Agencies',
        TI: 'Tour Operators & Arrangers',
        TJ: 'Lodging',
        TK: 'Gaming',
        TL: 'Car Rental',
        TM: 'Freight Forwarders & Arrangers',
        TN: 'Global Dist. Systems/CRS',
        TO: 'Freight Airlines',
        TP: 'Truck Rental & Leasing',
        TQ: 'Passenger Water Transportation',
        TR: 'Port Operations',
        TW: 'Travel & Transportation NetGen',
    },
    W: {
        WM: 'Wholesale- General Trading Co.',
        WN: 'Wholesale- Food/Food Svc/Drug',
        WO: 'Wholesale- Non-Durables',
        WP: 'Wholesale- Durables',
        WQ: 'Wholesale- Services',
        WW: 'Wholesale Distribution & Services NetGen',
    },
}


type JobFunctionKey = keyof typeof JOB_FUNCTION;
type IndustryKey = keyof typeof INDUSTRY;

type SubIndustry = typeof SUB_INDUSTRY[keyof typeof SUB_INDUSTRY];
type SubIndustryKey = KeysOfUnion<SubIndustry>;


export type {JobFunctionKey, IndustryKey, SubIndustryKey}
export {JOB_FUNCTION, INDUSTRY, SUB_INDUSTRY};