// Address
import {KeysOfUnion} from "@/app/types/utils";

const COUNTRY = {
    '': '',
    'US': 'United States of America',
    'AF': 'Afghanistan',
    'AX': 'Åland Islands',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'AS': 'American Samoa',
    'AD': 'Andorra',
    'AO': 'Angola',
    'AI': 'Anguilla',
    'AQ': 'Antarctica',
    'AG': 'Antigua and Barbuda',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AW': 'Aruba',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BS': 'Bahamas',
    'BH': 'Bahrain',
    'BD': 'Bangladesh',
    'BB': 'Barbados',
    'BE': 'Belgium',
    'BZ': 'Belize',
    'BJ': 'Benin',
    'BM': 'Bermuda',
    'BT': 'Bhutan',
    'BO': 'Bolivia, Plurinational State of',
    'BQ': 'Bonaire, Sint Eustatius and Saba',
    'BA': 'Bosnia and Herzegovina',
    'BW': 'Botswana',
    'BV': 'Bouvet Island',
    'BR': 'Brazil',
    'IO': 'British Indian Ocean Territory',
    'BN': 'Brunei Darussalam',
    'BG': 'Bulgaria',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'KH': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'CV': 'Cape Verde',
    'KY': 'Cayman Islands',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CL': 'Chile',
    'CN': 'China',
    'CX': 'Christmas Island',
    'CC': 'Cocos (Keeling) Islands',
    'CO': 'Colombia',
    'KM': 'Comoros',
    'CG': 'Congo',
    'CD': 'Congo, The Democratic Republic of the',
    'CK': 'Cook Islands',
    'CR': 'Costa Rica',
    'CI': 'Côte d\'Ivoire',
    'HR': 'Croatia',
    'CW': 'Curaçao',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DK': 'Denmark',
    'DJ': 'Djibouti',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'SV': 'El Salvador',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EE': 'Estonia',
    'SZ': 'Eswatini',
    'ET': 'Ethiopia',
    'FK': 'Falkland Islands (Malvinas)',
    'FO': 'Faroe Islands',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'GF': 'French Guiana',
    'PF': 'French Polynesia',
    'TF': 'French Southern Territories',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GR': 'Greece',
    'GL': 'Greenland',
    'GD': 'Grenada',
    'GP': 'Guadeloupe',
    'GU': 'Guam',
    'GT': 'Guatemala',
    'GG': 'Guernsey',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HT': 'Haiti',
    'HM': 'Heard Island and McDonald Islands',
    'VA': 'Holy See (Vatican City State)',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IM': 'Isle of Man',
    'IL': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'JE': 'Jersey',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KI': 'Kiribati',
    'KR': 'Korea, Republic of',
    'KW': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': 'Lao People\'s Democratic Republic',
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MO': 'Macao',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'MH': 'Marshall Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'YT': 'Mayotte',
    'MX': 'Mexico',
    'FM': 'Micronesia, Federated States of',
    'MD': 'Moldova, Republic of',
    'MC': 'Monaco',
    'MN': 'Mongolia',
    'ME': 'Montenegro',
    'MS': 'Montserrat',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibia',
    'NR': 'Nauru',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'NC': 'New Caledonia',
    'NZ': 'New Zealand',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'NU': 'Niue',
    'NF': 'Norfolk Island',
    'MK': 'North Macedonia',
    'MP': 'Northern Mariana Islands',
    'NO': 'Norway',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PW': 'Palau',
    'PS': 'Palestine, State of',
    'PA': 'Panama',
    'PG': 'Papua New Guinea',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PN': 'Pitcairn',
    'PL': 'Poland',
    'PT': 'Portugal',
    'PR': 'Puerto Rico',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Romania',
    'RW': 'Rwanda',
    'BL': 'Saint Barthélemy',
    'SH': 'Saint Helena, Ascension and Tristan da Cunha',
    'KN': 'Saint Kitts and Nevis',
    'LC': 'Saint Lucia',
    'MF': 'Saint Martin (French Part)',
    'PM': 'Saint Pierre and Miquelon',
    'VC': 'Saint Vincent and the Grenadines',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'ST': 'Sao Tome and Principe',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SG': 'Singapore',
    'SX': 'Sint Maarten (Dutch part)',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'SB': 'Solomon Islands',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'GS': 'South Georgia and the South Sandwich Islands',
    'SS': 'South Sudan',
    'ES': 'Spain',
    'LK': 'Sri Lanka',
    'SD': 'Sudan',
    'SR': 'Suriname',
    'SJ': 'Svalbard and Jan Mayen',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'TW': 'Taiwan',
    'TJ': 'Tajikistan',
    'TZ': 'Tanzania, United Republic of',
    'TH': 'Thailand',
    'TL': 'Timor-Leste',
    'TG': 'Togo',
    'TK': 'Tokelau',
    'TO': 'Tonga',
    'TT': 'Trinidad and Tobago',
    'TN': 'Tunisia',
    'TR': 'Türkiye',
    'TM': 'Turkmenistan',
    'TC': 'Turks and Caicos Islands',
    'TV': 'Tuvalu',
    'UG': 'Uganda',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom',
    'UM': 'United States Minor Outlying Islands',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VU': 'Vanuatu',
    'VE': 'Venezuela, Bolivarian Republic of',
    'VN': 'Viet Nam',
    'VG': 'Virgin Islands, British',
    'VI': 'Virgin Islands, U.S.',
    'WF': 'Wallis and Futuna',
    'EH': 'Western Sahara',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
}

const STATE_PROVINCE: Record<CountryKey, Record<string, string>> = {
    '': {'': ''},
    'AF': {
        'BAL': 'Balkh',
        'BAM': 'Bamyan',
        'BDG': 'Badghis',
        'BDS': 'Badakhshan',
        'BGL': 'Baghlan',
        'DAY': 'Daykundi',
        'FRA': 'Farah',
        'FYB': 'Faryab',
        'GHA': 'Ghazni',
        'GHO': 'Ghor',
        'HEL': 'Helmand',
        'HER': 'Herat',
        'JOW': 'Jowzjan',
        'KAB': 'Kabul',
        'KAN': 'Kandahar',
        'KAP': 'Kapisa',
        'KDZ': 'Kunduz',
        'KHO': 'Khost',
        'KNR': 'Kunar',
        'LAG': 'Laghman',
        'LOG': 'Logar',
        'NAN': 'Nangarhar',
        'NIM': 'Nimruz',
        'NUR': 'Nuristan',
        'PAN': 'Panjshir',
        'PAR': 'Parwan',
        'SAM': 'Samangan',
        'SAR': 'Sar-e Pol',
        'TAK': 'Takhar',
        'URU': 'Uruzgan',
        'WAR': 'Wardak',
        'ZAB': 'Zabul'
    },
    'AX': {
        'MAR': 'Mariehamn',
        'JOM': 'Jomala',
        'ECK': 'Eckerö',
        'FIN': 'Finström',
        'FOG': 'Föglö',
        'GET': 'Geta',
        'HAM': 'Hammarland',
        'KUM': 'Kumlinge',
        'KOK': 'Kökar',
        'LEM': 'Lemland',
        'LUM': 'Lumparland',
        'SAL': 'Saltvik',
        'SOT': 'Sottunga',
        'SUN': 'Sund',
        'VAR': 'Vårdö',
        'BRA': 'Brändö'
    },
    'AL': {
        '01': 'Berat',
        '02': 'Durrës',
        '03': 'Elbasan',
        '04': 'Fier',
        '05': 'Gjirokastër',
        '06': 'Korçë',
        '07': 'Kukës',
        '08': 'Lezhë',
        '09': 'Dibër',
        '10': 'Shkodër',
        '11': 'Tiranë',
        '12': 'Vlorë'
    },
    'DZ': {
        '01': 'Adrar',
        '02': 'Chlef',
        '03': 'Laghouat',
        '04': 'Oum El Bouaghi',
        '05': 'Batna',
        '06': 'Béjaïa',
        '07': 'Biskra',
        '08': 'Béchar',
        '09': 'Blida',
        '10': 'Bouira',
        '11': 'Tamanrasset',
        '12': 'Tébessa',
        '13': 'Tlemcen',
        '14': 'Tiaret',
        '15': 'Tizi Ouzou',
        '16': 'Alger',
        '17': 'Djelfa',
        '18': 'Jijel',
        '19': 'Sétif',
        '20': 'Saïda',
        '21': 'Skikda',
        '22': 'Sidi Bel Abbès',
        '23': 'Annaba',
        '24': 'Guelma',
        '25': 'Constantine',
        '26': 'Médéa',
        '27': 'Mostaganem',
        '28': 'M’Sila',
        '29': 'Mascara',
        '30': 'Ouargla',
        '31': 'Oran',
        '32': 'El Bayadh',
        '33': 'Illizi',
        '34': 'Bordj Bou Arréridj',
        '35': 'Boumerdès',
        '36': 'El Tarf',
        '37': 'Tindouf',
        '38': 'Tissemsilt',
        '39': 'El Oued',
        '40': 'Khenchela',
        '41': 'Souk Ahras',
        '42': 'Tipaza',
        '43': 'Mila',
        '44': 'Aïn Defla',
        '45': 'Naâma',
        '46': 'Aïn Témouchent',
        '47': 'Ghardaïa',
        '48': 'Relizane',
        '49': 'Timimoun',
        '50': 'Bordj Badji Mokhtar',
        '51': 'Ouled Djellal',
        '52': 'Béni Abbès',
        '53': 'In Salah',
        '54': 'In Guezzam',
        '55': 'Touggourt',
        '56': 'Djanet',
        '57': 'El M’Ghair',
        '58': 'El Meniaa'
    },
    'AS': {
        'E': 'Eastern District',
        'W': 'Western District',
        'M': 'Manu‘a District',
        'S': 'Swains Island',
        'R': 'Rose Atoll',
    },
    'AD': {
        '02': 'Canillo',
        '03': 'Encamp',
        '04': 'La Massana',
        '05': 'Ordino',
        '06': 'Sant Julià de Lòria',
        '07': 'Andorra la Vella',
        '08': 'Escaldes-Engordany',
    },
    'AO': {
        'BGO': 'Bengo',
        'BGU': 'Benguela',
        'BIE': 'Bié',
        'CAB': 'Cabinda',
        'CCU': 'Cuando Cubango',
        'CNN': 'Cunene',
        'CNO': 'Cuanza Norte',
        'CUS': 'Cuanza Sul',
        'HUA': 'Huambo',
        'HUI': 'Huíla',
        'LNO': 'Lunda Norte',
        'LSU': 'Lunda Sul',
        'LUA': 'Luanda',
        'MAL': 'Malanje',
        'MOX': 'Moxico',
        'NAM': 'Namibe',
        'UIG': 'Uíge',
        'ZAI': 'Zaire',
    },
    'AI': {
        'AN': 'Anguilla',
    },
    'AQ': {
        'AN': 'Antarctica',
    },
    'AG': {
        '03': 'Saint George',
        '04': 'Saint John',
        '05': 'Saint Mary',
        '06': 'Saint Paul',
        '07': 'Saint Peter',
        '08': 'Saint Philip',
        '10': 'Barbuda',
        '11': 'Redonda',
    },
    'AR': {
        'C': 'Ciudad Autónoma de Buenos Aires',
        'B': 'Buenos Aires',
        'K': 'Catamarca',
        'H': 'Chaco',
        'U': 'Chubut',
        'X': 'Córdoba',
        'W': 'Corrientes',
        'E': 'Entre Ríos',
        'P': 'Formosa',
        'Y': 'Jujuy',
        'L': 'La Pampa',
        'F': 'La Rioja',
        'M': 'Mendoza',
        'N': 'Misiones',
        'Q': 'Neuquén',
        'R': 'Río Negro',
        'A': 'Salta',
        'J': 'San Juan',
        'D': 'San Luis',
        'Z': 'Santa Cruz',
        'S': 'Santa Fe',
        'G': 'Santiago del Estero',
        'V': 'Tierra del Fuego',
        'T': 'Tucumán'
    },
    'AM': {
        'ER': 'Yerevan',
        'AG': 'Aragatsotn',
        'AR': 'Ararat',
        'AV': 'Armavir',
        'GR': 'Gegharkunik',
        'KT': 'Kotayk',
        'LO': 'Lori',
        'SH': 'Shirak',
        'SU': 'Syunik',
        'TV': 'Tavush',
        'VD': 'Vayots Dzor'
    },
    'AW': {
        'NO': 'Noord/Tanki Leendert',
        'OR': 'Oranjestad East',
        'OE': 'Oranjestad West',
        'PA': 'Paradera',
        'SI': 'Santa Cruz',
        'SA': 'Savaneta',
        'SN': 'San Nicolas North',
        'SS': 'San Nicolas South'
    },

    'AU': {
        'ACT': 'Australian Capital Territory',
        'NSW': 'New South Wales',
        'NT': 'Northern Territory',
        'QLD': 'Queensland',
        'SA': 'South Australia',
        'TAS': 'Tasmania',
        'VIC': 'Victoria',
        'WA': 'Western Australia',
        'CC': 'Cocos (Keeling) Islands',
        'CX': 'Christmas Island',
        'HM': 'Heard Island and McDonald Islands',
        'NF': 'Norfolk Island'
    },
    'AT': {
        '1': 'Burgenland',
        '2': 'Kärnten (Carinthia)',
        '3': 'Niederösterreich (Lower Austria)',
        '4': 'Oberösterreich (Upper Austria)',
        '5': 'Salzburg',
        '6': 'Steiermark (Styria)',
        '7': 'Tirol (Tyrol)',
        '8': 'Vorarlberg',
        '9': 'Wien (Vienna)'
    },
    'AZ': {
        'ABS': 'Abşeron',
        'AGA': 'Ağstafa',
        'AGC': 'Ağcabədi',
        'AGD': 'Ağdaş',
        'AGU': 'Ağsu',
        'AST': 'Astara',
        'BA': 'Bakı (Baku)',
        'BAL': 'Balakən',
        'BAR': 'Bərdə',
        'BEY': 'Beyləqan',
        'BIL': 'Biləsuvar',
        'CAB': 'Cəbrayıl',
        'CAL': 'Cəlilabad',
        'DAS': 'Daşkəsən',
        'FUZ': 'Füzuli',
        'GAD': 'Gədəbəy',
        'GA': 'Gəncə (Ganja)',
        'GOR': 'Goranboy',
        'GOY': 'Göyçay',
        'HAC': 'Hacıqabul',
        'IMI': 'İmişli',
        'ISM': 'İsmayıllı',
        'KAL': 'Kəlbəcər',
        'KUR': 'Kürdəmir',
        'LA': 'Lənkəran (City)',
        'LAN': 'Lənkəran (District)',
        'LER': 'Lerik',
        'MAS': 'Masallı',
        'NA': 'Naftalan (City)',
        'NX': 'Naxçıvan (Autonomous Republic)',
    },
    'BS': {
        'AK': 'Acklins',
        'BI': 'Bimini',
        'BP': 'Black Point',
        'BY': 'Berry Islands',
        'CE': 'Central Eleuthera',
        'CI': 'Cat Island',
        'CK': 'Crooked Island and Long Cay',
        'CO': 'Central Abaco',
        'CS': 'Central Andros',
        'EG': 'East Grand Bahama',
        'EX': 'Exuma',
        'FP': 'Freeport',
        'GH': 'Green Turtle Cay',
        'GC': 'Grand Cay',
        'HI': 'Harbour Island',
        'HT': 'Hope Town',
        'IN': 'Inagua',
        'LI': 'Long Island',
        'MC': 'Mangrove Cay',
        'MG': 'Mayaguana',
        'MI': 'Moore’s Island',
        'NE': 'North Eleuthera',
        'NO': 'North Abaco',
        'NS': 'North Andros',
        'RC': 'Rum Cay',
        'RI': 'Ragged Island',
        'SA': 'South Andros',
        'SE': 'South Eleuthera',
        'SO': 'South Abaco',
        'SS': 'San Salvador',
        'WG': 'West Grand Bahama',

        'NP': 'New Providence',
    },
    'BH': {
        '13': 'Capital',
        '14': 'Muharraq',
        '15': 'Northern',
        '17': 'Southern'
    },
    'BD': {
        '01': 'Barishal',
        '02': 'Chattogram',
        '03': 'Dhaka',
        '04': 'Khulna',
        '05': 'Rajshahi',
        '06': 'Rangpur',
        '07': 'Sylhet',
        '08': 'Mymensingh'
    },
    'BB': {
        '01': 'Christ Church',
        '02': 'Saint Andrew',
        '03': 'Saint George',
        '04': 'Saint James',
        '05': 'Saint John',
        '06': 'Saint Joseph',
        '07': 'Saint Lucy',
        '08': 'Saint Michael',
        '09': 'Saint Peter',
        '10': 'Saint Philip',
        '11': 'Saint Thomas'
    },
    'BE': {

        'BRU': 'Brussels-Capital Region',
        'VLG': 'Flemish Region',
        'WAL': 'Walloon Region',
        'VAN': 'Antwerp',
        'VLI': 'Limburg',
        'VOV': 'East Flanders',
        'VBR': 'Flemish Brabant',
        'VWV': 'West Flanders',
        'WBR': 'Walloon Brabant',
        'WHT': 'Hainaut',
        'WLG': 'Liège',
        'WLX': 'Luxembourg',
        'WNA': 'Namur',
    },
    'BZ': {
        'BZ': 'Belize District',
        'CY': 'Cayo',
        'CZL': 'Corozal',
        'OW': 'Orange Walk',
        'SC': 'Stann Creek',
        'TOL': 'Toledo',
    },
    'BJ': {
        'AL': 'Alibori',
        'AK': 'Atakora',
        'AQ': 'Atlantique',
        'BO': 'Borgou',
        'CO': 'Collines',
        'DO': 'Donga',
        'KO': 'Kouffo',
        'LI': 'Li̅ttoral',
        'MO': 'Mono',
        'OU': 'Ouémé',
        'PL': 'Plateau',
        'ZO': 'Zou'
    },
    'BM': {
        'DEV': 'Devonshire',
        'HAM': 'Hamilton Parish',
        'PAG': 'Paget',
        'PEM': 'Pembroke',
        'SAI': 'Saint George’s',
        'SAN': 'Sandys',
        'SMI': 'Smith’s',
        'SOU': 'Southampton',
        'WAR': 'Warwick',
        'HMT': 'Hamilton (City)',
        'SGE': 'St. George’s (Town)'
    },
    'BT': {
        '11': 'Paro',
        '12': 'Chhukha',
        '13': 'Ha',
        '14': 'Samtse',
        '15': 'Thimphu',
        '21': 'Tsirang',
        '22': 'Dagana',
        '23': 'Punakha',
        '24': 'Gasa',
        '31': 'Wangdue Phodrang',
        '32': 'Sarpang',
        '33': 'Trongsa',
        '34': 'Bumthang',
        '35': 'Zhemgang',
        '41': 'Trashigang',
        '42': 'Monggar',
        '43': 'Lhuentse',
        '44': 'Trashi Yangtse',
        '45': 'Pemagatshel',
        '46': 'Samdrup Jongkha'
    },
    'BO': {
        'B': 'El Beni',
        'C': 'Cochabamba',
        'H': 'Chuquisaca',
        'L': 'La Paz',
        'N': 'Pando',
        'O': 'Oruro',
        'P': 'Potosí',
        'S': 'Santa Cruz',
        'T': 'Tarija'
    },
    'BQ': {
        'BO': 'Bonaire',
        'SA': 'Saba',
        'SE': 'Sint Eustatius',
    },
    'BA': {

        'BIH': 'Federation of Bosnia and Herzegovina',
        'SRP': 'Republika Srpska',
        'BRC': 'Brčko District',


        '01': 'Una-Sana Canton',
        '02': 'Posavina Canton',
        '03': 'Tuzla Canton',
        '04': 'Zenica-Doboj Canton',
        '05': 'Bosnian-Podrinje Goražde',
        '06': 'Central Bosnia Canton',
        '07': 'Herzegovina-Neretva Canton',
        '08': 'West Herzegovina Canton',
        '09': 'Sarajevo Canton',
        '10': 'Canton 10 (Hercegbosanski)',
    },
    'BW': {
        'CE': 'Central',
        'GH': 'Ghanzi',
        'KG': 'Kgalagadi',
        'KL': 'Kgatleng',
        'KW': 'Kweneng',
        'NG': 'Ngamiland',
        'NE': 'North-East',
        'NW': 'North-West',
        'SE': 'South-East',
        'SO': 'Southern',
    },
    'BV': {
        'BI': 'Bouvet Island',
    },
    'BR': {
        'AC': 'Acre',
        'AL': 'Alagoas',
        'AM': 'Amazonas',
        'AP': 'Amapá',
        'BA': 'Bahia',
        'CE': 'Ceará',
        'DF': 'Distrito Federal',
        'ES': 'Espírito Santo',
        'GO': 'Goiás',
        'MA': 'Maranhão',
        'MT': 'Mato Grosso',
        'MS': 'Mato Grosso do Sul',
        'MG': 'Minas Gerais',
        'PA': 'Pará',
        'PB': 'Paraíba',
        'PR': 'Paraná',
        'PE': 'Pernambuco',
        'PI': 'Piauí',
        'RJ': 'Rio de Janeiro',
        'RN': 'Rio Grande do Norte',
        'RO': 'Rondônia',
        'RR': 'Roraima',
        'RS': 'Rio Grande do Sul',
        'SC': 'Santa Catarina',
        'SE': 'Sergipe',
        'SP': 'São Paulo',
        'TO': 'Tocantins',
    },
    'IO': {
        'BIOT': 'British Indian Ocean Territory',
    },
    'BN': {
        'BE': 'Belait',
        'BM': 'Brunei-Muara',
        'TE': 'Temburong',
        'TU': 'Tutong',
    },
    'BG': {
        '01': 'Blagoevgrad',
        '02': 'Burgas',
        '03': 'Varna',
        '04': 'Veliko Tarnovo',
        '05': 'Vidin',
        '06': 'Vratsa',
        '07': 'Gabrovo',
        '08': 'Dobrich',
        '09': 'Kardzhali',
        '10': 'Kyustendil',
        '11': 'Lovech',
        '12': 'Montana',
        '13': 'Pazardzhik',
        '14': 'Pernik',
        '15': 'Pleven',
        '16': 'Plovdiv',
        '17': 'Razgrad',
        '18': 'Ruse',
        '19': 'Silistra',
        '20': 'Sliven',
        '21': 'Smolyan',
        '22': 'Sofia-Grad',
        '23': 'Sofia',
        '24': 'Stara Zagora',
        '25': 'Targovishte',
        '26': 'Haskovo',
        '27': 'Shumen',
        '28': 'Yambol',
    },
    'BF': {
        '01': 'Boucle du Mouhoun',
        '02': 'Cascades',
        '03': 'Centre',
        '04': 'Centre-Est',
        '05': 'Centre-Nord',
        '06': 'Centre-Ouest',
        '07': 'Centre-Sud',
        '08': 'Est',
        '09': 'Hauts-Bassins',
        '10': 'Nord',
        '11': 'Plateau-Central',
        '12': 'Sahel',
        '13': 'Sud-Ouest',
    },
    'BI': {
        'BB': 'Bubanza',
        'BJ': 'Bujumbura',
        'BM': 'Bujumbura Mairie',
        'BL': 'Bujumbura Rural',
        'BR': 'Bururi',
        'CA': 'Cankuzo',
        'CI': 'Cibitoke',
        'GI': 'Gitega',
        'KI': 'Kirundo',
        'KR': 'Karuzi',
        'KY': 'Kayanza',
        'MA': 'Makamba',
        'MU': 'Muramvya',
        'MW': 'Mwaro',
        'MY': 'Muyinga',
        'NG': 'Ngozi',
        'RM': 'Rumonge',
        'RT': 'Rutana',
    },
    'KH': {
        '1': 'Banteay Meanchey',
        '10': 'Kampong Cham',
        '11': 'Kampong Chhnang',
        '12': 'Kampong Speu',
        '13': 'Kampong Thom',
        '14': 'Kampot',
        '15': 'Kandal',
        '16': 'Koh Kong',
        '17': 'Kratie',
        '18': 'Mondulkiri',
        '19': 'Phnom Penh',
        '2': 'Battambang',
        '20': 'Preah Vihear',
        '21': 'Prey Veng',
        '22': 'Pursat',
        '23': 'Ratanakiri',
        '24': 'Siem Reap',
        '25': 'Preah Sihanouk',
        '26': 'Stung Treng',
        '27': 'Svay Rieng',
        '28': 'Takéo',
        '29': 'Oddar Meanchey',
        '3': 'Kampong Cham (deprecated old code)',
        '30': 'Kep',
        '31': 'Pailin',
        '32': 'Tbong Khmum'
    },
    'CM': {
        'AD': 'Adamaoua',
        'CE': 'Centre',
        'ES': 'East',
        'EN': 'Far North',
        'LT': 'Littoral',
        'NO': 'North',
        'NW': 'North-West',
        'OU': 'West',
        'SU': 'South',
        'SW': 'South-West',
    },
    'CA': {
        'AB': 'Alberta',
        'BC': 'British Columbia',
        'MB': 'Manitoba',
        'NB': 'New Brunswick',
        'NL': 'Newfoundland and Labrador',
        'NS': 'Nova Scotia',
        'NT': 'Northwest Territories',
        'NU': 'Nunavut',
        'ON': 'Ontario',
        'PE': 'Prince Edward Island',
        'QC': 'Quebec',
        'SK': 'Saskatchewan',
        'YT': 'Yukon',
    },
    'CV': {
        'BV': 'Boa Vista',
        'BR': 'Brava',
        'CS': 'Calheta de São Miguel',
        'MA': 'Maio',
        'MO': 'Mosteiros',
        'PA': 'Paul',
        'PN': 'Porto Novo',
        'PR': 'Praia',
        'RB': 'Ribeira Brava',
        'RG': 'Ribeira Grande',
        'RS': 'Ribeira Grande de Santiago',
        'SD': 'Santa Catarina do Fogo',
        'SF': 'São Filipe',
        'SL': 'Sal',
        'SM': 'Santa Catarina',
        'SN': 'São Nicolau',
        'SO': 'São Lourenço dos Órgãos',
        'SS': 'São Salvador do Mundo',
        'SV': 'São Vicente',
        'TA': 'Tarrafal',
        'TS': 'Tarrafal de São Nicolau',
        'TZ': 'Tarrafal (deprecated code—use TS?)',
    },
    'KY': {
        'CI': 'Cayman Islands',
    },
    'CF': {
        'BB': 'Bamingui-Bangoran',
        'BK': 'Basse-Kotto',
        'HK': 'Haute-Kotto',
        'HM': 'Haut-Mbomou',
        'HS': 'Haute-Sangha / Mambéré-Kadéï',
        'KB': 'Gribingui',
        'KG': 'Kémo',
        'LB': 'Lobaye',
        'MB': 'Mbomou',
        'MP': 'Ombella-M’Poko',
        'NM': 'Nana-Mambéré',
        'OP': 'Ouham-Pendé',
        'SE': 'Sangha',
        'UK': 'Ouaka',
        'VK': 'Vakaga',
        'AC': 'Bangui (Autonomous Commune)',
        'BKO': 'Bangoran (Economic Prefecture, older code BB?)',
    },
    'TD': {
        'BA': 'Batha',
        'BG': 'Bagirmi',
        'BO': 'Borkou',
        'CB': 'Chari-Baguirmi',
        'EN': 'Ennedi-Est',
        'EO': 'Ennedi-Ouest',
        'GR': 'Guéra',
        'KA': 'Kanem',
        'LC': 'Lac',
        'LO': 'Logone-Occidental',
        'LR': 'Logone-Oriental',
        'MA': 'Mandoul',
        'ME': 'Mayo-Kebbi-Est',
        'MO': 'Mayo-Kebbi-Ouest',
        'MEF': 'Moyen-Chari (sometimes MC)',
        'ND': 'N’Djamena',
        'OD': 'Ouaddaï',
        'SA': 'Salamat',
        'SI': 'Sila',
        'TA': 'Tandjilé',
        'TI': 'Tibesti',
        'WF': 'Wadi Fira',
        'HL': 'Hadjer-Lamis',
    },
    'CL': {
        'AI': 'Aisén del General Carlos Ibáñez del Campo',
        'AN': 'Antofagasta',
        'AP': 'Arica y Parinacota',
        'AR': 'La Araucanía',
        'AT': 'Atacama',
        'BI': 'Biobío',
        'CO': 'Coquimbo',
        'LI': 'Libertador General Bernardo O’Higgins',
        'LL': 'Los Lagos',
        'LR': 'Los Ríos',
        'MA': 'Magallanes',
        'ML': 'Maule',
        'NB': 'Ñuble',
        'RM': 'Región Metropolitana de Santiago',
        'TA': 'Tarapacá',
        'VS': 'Valparaíso',
    },
    'CN': {
        'BJ': 'Beijing',
        'SH': 'Shanghai',
        'TJ': 'Tianjin',
        'CQ': 'Chongqing',
        'HE': 'Hebei',
        'SX': 'Shanxi',
        'LN': 'Liaoning',
        'JL': 'Jilin',
        'HL': 'Heilongjiang',
        'JS': 'Jiangsu',
        'ZJ': 'Zhejiang',
        'AH': 'Anhui',
        'FJ': 'Fujian',
        'JX': 'Jiangxi',
        'SD': 'Shandong',
        'HA': 'Henan',
        'HB': 'Hubei',
        'HN': 'Hunan',
        'GD': 'Guangdong',
        'HAI': 'Hainan',
        'SC': 'Sichuan',
        'GZ': 'Guizhou',
        'YN': 'Yunnan',
        'SN': 'Shaanxi',
        'GS': 'Gansu',
        'QH': 'Qinghai',
        'TW': 'Taiwan',
        'GX': 'Guangxi Zhuang',
        'NM': 'Inner Mongolia',
        'XZ': 'Tibet (Xizang)',
        'NX': 'Ningxia Hui',
        'XJ': 'Xinjiang Uyghur',
        'HK': 'Hong Kong',
        'MO': 'Macao',
    },
    'CX': {
        'CI': 'Christmas Island',
    },
    'CC': {
        'CI': 'Cocos (Keeling) Islands',
    },
    'CO': {
        'AMA': 'Amazonas',
        'ANT': 'Antioquia',
        'ARA': 'Arauca',
        'ATL': 'Atlántico',
        'BOL': 'Bolívar',
        'BOY': 'Boyacá',
        'CAL': 'Caldas',
        'CAQ': 'Caquetá',
        'CAS': 'Casanare',
        'CAU': 'Cauca',
        'CES': 'Cesar',
        'CHO': 'Chocó',
        'COR': 'Córdoba',
        'CUN': 'Cundinamarca',
        'DC': 'Distrito Capital de Bogotá',
        'GUA': 'Guainía',
        'GUV': 'Guaviare',
        'HUI': 'Huila',
        'LAG': 'La Guajira',
        'MAG': 'Magdalena',
        'MET': 'Meta',
        'NAR': 'Nariño',
        'NSA': 'Norte de Santander',
        'PAT': 'Putumayo',
        'QUI': 'Quindío',
        'RIS': 'Risaralda',
        'SAN': 'Santander',
        'SAP': 'San Andrés, Providencia y Santa Catalina',
        'SUC': 'Sucre',
        'TOL': 'Tolima',
        'VAC': 'Valle del Cauca',
        'VAU': 'Vaupés',
        'VID': 'Vichada',
    },
    'KM': {
        'A': 'Anjouan (Ndzuwani)',
        'G': 'Grande Comore (Njazidja)',
        'M': 'Mohéli (Mwali)',
    },
    'CG': {
        '11': 'Bouenza',
        '12': 'Brazzaville',
        '13': 'Cuvette',
        '14': 'Cuvette-Ouest',
        '15': 'Kouilou',
        '16': 'Lékoumou',
        '2': 'Likouala',
        '5': 'Plateaux',
        '7': 'Pool',
        '8': 'Sangha',
        '9': 'Niari',
        'CU': 'Ngöbe? (Some older references may differ)',
    },
    'CD': {
        'BC': 'Kongo Central (Bas-Congo)',
        'BU': 'Bas-Uélé',
        'EQ': 'Équateur',
        'HK': 'Haut-Katanga',
        'HL': 'Haut-Lomami',
        'HU': 'Haut-Uélé',
        'IT': 'Ituri',
        'KC': 'Kasai Central',
        'KD': 'Kasai',
        'KE': 'Kasai Oriental',
        'KN': 'Kinshasa',
        'KS': 'Kwango',
        'KW': 'Kwilu',
        'LO': 'Lomami',
        'LU': 'Lualaba',
        'MA': 'Maniema',
        'MN': 'Mai-Ndombe',
        'MO': 'Mongala',
        'NK': 'Nord-Kivu',
        'NU': 'Nord-Ubangi',
        'SA': 'Sankuru',
        'SK': 'Sud-Kivu',
        'SU': 'Sud-Ubangi',
        'TA': 'Tanganyika',
        'TU': 'Tshopo',
        'TU2': 'Tshuapa',
    },
    'CK': {
        'CI': 'Cook Islands',
    },
    'CR': {
        'A': 'Alajuela',
        'C': 'Cartago',
        'G': 'Guanacaste',
        'H': 'Heredia',
        'L': 'Limón',
        'P': 'Puntarenas',
        'SJ': 'San José',
    },
    'CI': {
        'AB': 'Abidjan (Autonomous District)',
        'BS': 'Bas-Sassandra',
        'CM': 'Comoé',
        'DN': 'Denguélé',
        'GD': 'Gôh-Djiboua',
        'LC': 'Lacs',
        'LG': 'Lagunes',
        'MG': 'Montagnes',
        'SM': 'Sassandra-Marahoué',
        'SV': 'Savanes',
        'VB': 'Vallée du Bandama',
        'WR': 'Woroba',
        'YM': 'Yamoussoukro (Autonomous District)',
        'ZZ': 'Zanzan',
    },
    'HR': {
        '01': 'Zagrebačka',
        '02': 'Krapinsko-zagorska',
        '03': 'Sisačko-moslavačka',
        '04': 'Karlovačka',
        '05': 'Varaždinska',
        '06': 'Koprivničko-križevačka',
        '07': 'Bjelovarsko-bilogorska',
        '08': 'Primorsko-goranska',
        '09': 'Ličko-senjska',
        '10': 'Virovitičko-podravska',
        '11': 'Požeško-slavonska',
        '12': 'Brodsko-posavska',
        '13': 'Zadarska',
        '14': 'Osječko-baranjska',
        '15': 'Šibensko-kninska',
        '16': 'Vukovarsko-srijemska',
        '17': 'Splitsko-dalmatinska',
        '18': 'Istarska',
        '19': 'Dubrovačko-neretvanska',
        '20': 'Međimurska',
        '21': 'Grad Zagreb',
    },
    'CW': {
        'CR': 'Curaçao',
    },
    'CY': {
        '01': 'Famagusta (Ammóchostos)',
        '02': 'Kyrenia (Kýrenia)',
        '03': 'Larnaca (Lárnaka)',
        '04': 'Nicosia (Lefkosía)',
        '05': 'Limassol (Lemesós)',
        '06': 'Paphos (Páfos)',
    },
    'CZ': {
        'PR': 'Praha (Prague)',
        'ST': 'Středočeský',
        'JC': 'Jihočeský',
        'PL': 'Plzeňský',
        'KA': 'Karlovarský',
        'US': 'Ústecký',
        'LB': 'Liberecký',
        'HK': 'Královéhradecký',
        'PA': 'Pardubický',
        'VY': 'Vysočina',
        'JM': 'Jihomoravský',
        'OL': 'Olomoucký',
        'ZL': 'Zlínský',
        'MO': 'Moravskoslezský',
    },
    'DK': {
        '81': 'Nordjylland',
        '82': 'Midtjylland',
        '83': 'Syddanmark',
        '84': 'Hovedstaden',
        '85': 'Sjælland',
    },
    'DJ': {
        'AR': 'Arta',
        'AS': 'Ali Sabieh',
        'DI': 'Dikhil',
        'DJ': 'Djibouti City',
        'OB': 'Obock',
        'TA': 'Tadjourah',
        'DK': 'Dikhil',
    },
    'DM': {
        '01': 'Saint Peter',
        '02': 'Saint Andrew',
        '03': 'Saint David',
        '04': 'Saint George',
        '05': 'Saint John',
        '06': 'Saint Joseph',
        '07': 'Saint Luke',
        '08': 'Saint Mark',
        '09': 'Saint Patrick',
        '10': 'Saint Paul',
    },
    'DO': {
        '01': 'Distrito Nacional (Santo Domingo)',
        '02': 'Azua',
        '03': 'Baoruco',
        '04': 'Barahona',
        '05': 'Dajabón',
        '06': 'Duarte',
        '07': 'Elías Piña',
        '08': 'El Seibo',
        '09': 'Espaillat',
        '10': 'Independencia',
        '11': 'La Altagracia',
        '12': 'La Romana',
        '13': 'La Vega',
        '14': 'María Trinidad Sánchez',
        '15': 'Monte Cristi',
        '16': 'Pedernales',
        '17': 'Peravia',
        '18': 'Puerto Plata',
        '19': 'Salcedo (Hermanas Mirabal)',
        '20': 'Samaná',
        '21': 'San Cristóbal',
        '22': 'San Juan',
        '23': 'San Pedro de Macorís',
        '24': 'Sánchez Ramírez',
        '25': 'Santiago',
        '26': 'Santiago Rodríguez',
        '27': 'Valverde',
        '28': 'Monseñor Nouel',
        '29': 'Monte Plata',
        '30': 'Hato Mayor',
        '31': 'San José de Ocoa',
        '32': 'Santo Domingo',
    },
    'EC': {
        'A': 'Azuay',
        'B': 'Bolívar',
        'C': 'Carchi',
        'D': 'Orellana',
        'E': 'Esmeraldas',
        'F': 'Cañar',
        'G': 'Guayas',
        'H': 'Chimborazo',
        'I': 'Imbabura',
        'L': 'Loja',
        'M': 'Manabí',
        'N': 'Napo',
        'O': 'El Oro',
        'P': 'Pichincha',
        'R': 'Los Ríos',
        'S': 'Morona-Santiago',
        'SD': 'Santo Domingo de los Tsáchilas',
        'SE': 'Santa Elena',
        'T': 'Tungurahua',
        'U': 'Sucumbíos',
        'W': 'Galápagos',
        'X': 'Cotopaxi',
        'Y': 'Pastaza',
        'Z': 'Zamora-Chinchipe',
    },
    'EG': {
        'ALX': 'Alexandria',
        'ASN': 'Aswan',
        'AST': 'Asyut',
        'BA': 'Beheira',
        'BNS': 'Beni Suef',
        'C': 'Cairo',
        'DK': 'Dakahlia',
        'DT': 'Damietta',
        'FYM': 'Faiyum',
        'GH': 'Gharbia',
        'GZ': 'Giza',
        'IS': 'Ismailia',
        'JS': 'South Sinai (Janub Sina)',
        'KB': 'Qalyubia (Al Qalyubiyah)',
        'KFS': 'Kafr El Sheikh',
        'KN': 'Qena',
        'LX': 'Luxor (Al Uqsur)',
        'MN': 'Minya (Al Minya)',
        'MNF': 'Monufia (Al Minufiyah)',
        'MT': 'Matrouh (Marsa Matruh)',
        'PTS': 'Port Said',
        'SHG': 'Sohag',
        'SHR': 'Al Sharqia (Ash Sharqiyah)',
        'SIN': 'North Sinai (Shamal Sina)',
        'SUZ': 'Suez',
        'WAD': 'New Valley (Al Wadi al Jadid)',
        'BAH': 'Red Sea (Al Bahr al Ahmar)',
    },
    'SV': {
        'AH': 'Ahuachapán',
        'CA': 'Cabañas',
        'CH': 'Chalatenango',
        'CU': 'Cuscatlán',
        'LI': 'La Libertad',
        'PA': 'La Paz',
        'UN': 'La Unión',
        'MO': 'Morazán',
        'SM': 'San Miguel',
        'SS': 'San Salvador',
        'SA': 'Santa Ana',
        'SO': 'Sonsonate',
        'SV': 'San Vicente',
        'US': 'Usulután',
    },
    'GQ': {
        'AN': 'Annobón',
        'BN': 'Bioko Norte',
        'BS': 'Bioko Sur',
        'CS': 'Centro Sur',
        'KN': 'Kie-Ntem',
        'LI': 'Litoral',
        'WN': 'Wele-Nzas',
        'DJ': 'Djibloho (new province created in 2017)',
    },
    'ER': {
        'AN': 'Anelba (Anseba)',
        'DU': 'Al Janūbī (Debub)',
        'DK': 'Janūbī al Baḥrī al Aḥmar (Southern Red Sea)',
        'GB': 'Gash-Barka',
        'MA': 'Ma’ākel (Central)',
        'SK': 'Shimālī al Baḥrī al Aḥmar (Northern Red Sea)',
    },
    'EE': {
        '37': 'Harju',
        '39': 'Hiiu',
        '44': 'Ida-Viru',
        '49': 'Jõgeva',
        '51': 'Järva',
        '57': 'Lääne',
        '59': 'Lääne-Viru',
        '65': 'Põlva',
        '67': 'Pärnu',
        '70': 'Rapla',
        '74': 'Saare',
        '78': 'Tartu',
        '82': 'Valga',
        '84': 'Viljandi',
        '86': 'Võru',
    },
    'SZ': {
        'HH': 'Hhohho',
        'LU': 'Lubombo',
        'MA': 'Manzini',
        'SH': 'Shiselweni',
    },
    'ET': {
        'AA': 'Addis Ababa',
        'AF': 'Afar',
        'AM': 'Amhara',
        'BE': 'Benishangul-Gumuz',
        'DD': 'Dire Dawa',
        'GA': 'Gambela',
        'HA': 'Harari',
        'OR': 'Oromia',
        'SM': 'Somali',
        'SN': 'Southern Nations, Nationalities, and Peoples’',
        'SI': 'Sidama',
        'TI': 'Tigray',
    },
    'FK': {
        'FI': 'Falkland Islands (Islas Malvinas)',
    },
    'FO': {
        'FI': 'Faroe Islands',
    },
    'FJ': {
        'C': 'Central',
        'E': 'Eastern',
        'N': 'Northern',
        'R': 'Rotuma',
        'W': 'Western',
    },
    'FI': {
        '01': 'Åland',
        '02': 'South Karelia',
        '03': 'Southern Ostrobothnia',
        '04': 'Southern Savonia',
        '05': 'Kainuu',
        '06': 'Tavastia Proper (Kanta-Häme)',
        '07': 'Central Ostrobothnia',
        '08': 'Central Finland',
        '09': 'Kymenlaakso',
        '10': 'Lapland',
        '11': 'Pirkanmaa',
        '12': 'Ostrobothnia',
        '13': 'North Karelia',
        '14': 'Northern Ostrobothnia',
        '15': 'Northern Savonia',
        '16': 'Päijät-Häme',
        '17': 'Satakunta',
        '18': 'Uusimaa',
        '19': 'Southwest Finland (Varsinais-Suomi)',
    },
    'FR': {

        'ARA': 'Auvergne-Rhône-Alpes',
        'BFC': 'Bourgogne-Franche-Comté',
        'BRE': 'Bretagne',
        'CVL': 'Centre-Val de Loire',
        'COR': 'Corse',
        'GES': 'Grand Est',
        'HDF': 'Hauts-de-France',
        'IDF': 'Île-de-France',
        'NOR': 'Normandie',
        'NAQ': 'Nouvelle-Aquitaine',
        'OCC': 'Occitanie',
        'PAC': 'Provence-Alpes-Côte d’Azur',
        'PDL': 'Pays de la Loire',
        'GF': 'Guyane (French Guiana)',
        'GP': 'Guadeloupe',
        'MQ': 'Martinique',
        'RE': 'La Réunion',
        'YT': 'Mayotte',
    },
    'GF': {
        'FG': 'French Guiana',
    },
    'PF': {
        'FP': 'French Polynesia',
    },
    'TF': {
        'FST': 'French Southern Territories',
    },
    'GA': {
        '1': 'Estuaire',
        '2': 'Haut-Ogooué',
        '3': 'Moyen-Ogooué',
        '4': 'Ngounié',
        '5': 'Nyanga',
        '6': 'Ogooué-Ivindo',
        '7': 'Ogooué-Lolo',
        '8': 'Ogooué-Maritime',
        '9': 'Woleu-Ntem',
    },
    'GM': {
        'B': 'Banjul',
        'L': 'Lower River',
        'M': 'Central River',
        'N': 'North Bank',
        'U': 'Upper River',
        'W': 'West Coast',
    },
    'GE': {
        'AB': 'Abkhazia (disputed)',
        'AJ': 'Adjara (Adzharia)',
        'GU': 'Guria',
        'IM': 'Imereti',
        'KA': 'Kakheti',
        'KK': 'Kvemo Kartli',
        'MM': 'Mtskheta-Mtianeti',
        'RL': 'Racha-Lechkhumi and Kvemo Svaneti',
        'SJ': 'Samtskhe-Javakheti',
        'SZ': 'Samegrelo-Zemo Svaneti',
        'TB': 'Tbilisi (capital city)',
    },
    'DE': {
        'BW': 'Baden-Württemberg',
        'BY': 'Bayern (Bavaria)',
        'BE': 'Berlin',
        'BB': 'Brandenburg',
        'HB': 'Bremen',
        'HH': 'Hamburg',
        'HE': 'Hessen (Hesse)',
        'MV': 'Mecklenburg-Vorpommern',
        'NI': 'Niedersachsen (Lower Saxony)',
        'NW': 'Nordrhein-Westfalen',
        'RP': 'Rheinland-Pfalz (Rhineland-Palatinate)',
        'SL': 'Saarland',
        'SN': 'Sachsen (Saxony)',
        'ST': 'Sachsen-Anhalt',
        'SH': 'Schleswig-Holstein',
        'TH': 'Thüringen (Thuringia)',
    },
    'GH': {
        'AA': 'Greater Accra',
        'AH': 'Ashanti',
        'BA': 'Brong-Ahafo',
        'CP': 'Central',
        'EP': 'Eastern',
        'NP': 'Northern',
        'TV': 'Volta',
        'UE': 'Upper East',
        'UW': 'Upper West',
        'WP': 'Western',
        'AF': 'Ahafo',
        'BE': 'Bono East',
        'BO': 'Bono',
        'NE': 'North East',
        'OT': 'Oti',
        'SV': 'Savannah',
        'WN': 'Western North',
    },
    'GI': {
        'G': 'Gibraltar',
    },
    'GR': {
        'A': 'Anatolikí Makedonía kai Thráki',
        'I': 'Attikí',
        'G': 'Dytikí Elláda',
        'C': 'Dytikí Makedonía',
        'F': 'Ionía Nísia',
        'D': 'Ípeiros',
        'B': 'Kentrikí Makedonía',
        'M': 'Kríti (Crete)',
        'L': 'Notío Aigaío (South Aegean)',
        'J': 'Peloponnísos',
        'H': 'Stérea Elláda (Central Greece)',
        'E': 'Thessalía',
        'K': 'Voreío Aigaío (North Aegean)',
        '69': 'Ágion Óros (Mount Athos)',
    },
    'GL': {
        'G': 'Greenland',
    },
    'GD': {
        '01': 'Saint Andrew',
        '02': 'Saint David',
        '03': 'Saint George',
        '04': 'Saint John',
        '05': 'Saint Mark',
        '06': 'Saint Patrick',
        '10': 'Carriacou and Petite Martinique',
    },
    'GP': {
        'G': 'Guadeloupe',
    },
    'GU': {
        'G': 'Guam',
    },
    'GT': {
        'AV': 'Alta Verapaz',
        'BV': 'Baja Verapaz',
        'CM': 'Chimaltenango',
        'CQ': 'Chiquimula',
        'PR': 'El Progreso',
        'ES': 'Escuintla',
        'GU': 'Guatemala',
        'HU': 'Huehuetenango',
        'IZ': 'Izabal',
        'JA': 'Jalapa',
        'JU': 'Jutiapa',
        'PE': 'Petén',
        'QZ': 'Quetzaltenango',
        'QC': 'Quiché',
        'RE': 'Retalhuleu',
        'SA': 'Sacatepéquez',
        'SM': 'San Marcos',
        'SO': 'Sololá',
        'SR': 'Santa Rosa',
        'SU': 'Suchitepéquez',
        'TO': 'Totonicapán',
        'ZA': 'Zacapa',
    },
    'GG': {
        'G': 'Guernsey',
    },
    'GN': {
        'B': 'Boké',
        'C': 'Conakry (special zone)',
        'F': 'Faranah',
        'K': 'Kankan',
        'D': 'Kindia',
        'L': 'Labé',
        'M': 'Mamou',
        'N': 'Nzérékoré',
    },
    'GW': {
        'BA': 'Bafatá',
        'BM': 'Biombo',
        'BS': 'Bissau (autonomous)',
        'BL': 'Bolama/Bijagos',
        'CA': 'Cacheu',
        'GA': 'Gabú',
        'OI': 'Oio',
        'QU': 'Quinara',
        'TO': 'Tombali',
    },
    'GY': {
        'BA': 'Barima-Waini',
        'CU': 'Cuyuni-Mazaruni',
        'DE': 'Demerara-Mahaica',
        'EB': 'East Berbice-Corentyne',
        'ES': 'Essequibo Islands-West Demerara',
        'MA': 'Mahaica-Berbice',
        'PM': 'Pomeroon-Supenaam',
        'PT': 'Potaro-Siparuni',
        'UD': 'Upper Demerara-Berbice',
        'UT': 'Upper Takutu-Upper Essequibo',
    },
    'HT': {
        'AR': 'Artibonite',
        'CE': 'Centre',
        'GA': 'Grande’Anse',
        'ND': 'Nord',
        'NE': 'Nord-Est',
        'NI': 'Nippes',
        'NO': 'Nord-Ouest',
        'OU': 'Ouest',
        'SD': 'Sud',
        'SE': 'Sud-Est',
    },
    'HM': {
        'HI': 'Heard Island and McDonald Islands',
    },
    'VA': {
        'VC': 'Vatican City',
    },
    'HN': {
        'AT': 'Atlántida',
        'CH': 'Choluteca',
        'CL': 'Colón',
        'CM': 'Comayagua',
        'CP': 'Copán',
        'CR': 'Cortés',
        'EP': 'El Paraíso',
        'FM': 'Francisco Morazán',
        'GD': 'Gracias a Dios',
        'IB': 'Islas de la Bahía (Bay Islands)',
        'IN': 'Intibucá',
        'LE': 'Lempira',
        'LP': 'La Paz',
        'OC': 'Ocotepeque',
        'OL': 'Olancho',
        'SB': 'Santa Bárbara',
        'VA': 'Valle',
        'YO': 'Yoro',
    },
    'HK': {
        'HK': 'Hong Kong SAR',
    },
    'HU': {
        'BA': 'Baranya',
        'BC': 'Békéscsaba (City with county rights)',
        'BE': 'Békés',
        'BK': 'Bács-Kiskun',
        'BU': 'Budapest (capital city)',
        'BZ': 'Borsod-Abaúj-Zemplén',
        'CS': 'Csongrád-Csanád',
        'DE': 'Debrecen (City)',
        'DU': 'Dunaújváros (City)',
        'EG': 'Eger (City)',
        'ER': 'Érd (City)',
        'FE': 'Fejér',
        'GS': 'Győr-Moson-Sopron',
        'GY': 'Győr (City)',
        'HB': 'Hajdú-Bihar',
        'HE': 'Heves',
        'HV': 'Hódmezővásárhely (City)',
        'JN': 'Jász-Nagykun-Szolnok',
        'KE': 'Komárom-Esztergom',
        'KM': 'Kecskemét (City)',
        'KV': 'Kaposvár (City)',
        'MI': 'Miskolc (City)',
        'NK': 'Nagykanizsa (City)',
        'NO': 'Nógrád',
        'NY': 'Nyíregyháza (City)',
        'PE': 'Pest',
        'PS': 'Pécs (City)',
        'SD': 'Szeged (City)',
        'SH': 'Székesfehérvár (City)',
        'SK': 'Szolnok (City)',
        'SN': 'Sopron (City)',
        'SO': 'Somogy',
        'SS': 'Szombathely (City)',
        'SZ': 'Szabolcs-Szatmár-Bereg',
        'TB': 'Tatabánya (City)',
        'TO': 'Tolna',
        'VA': 'Vas',
        'VE': 'Veszprém',
        'VM': 'Veszprém (City)',
        'ZA': 'Zala',
        'ZE': 'Zalaegerszeg (City)',
    },
    'IS': {
        '1': 'Höfuðborgarsvæði (Capital Region)',
        '2': 'Suðurnes',
        '3': 'Vesturland',
        '4': 'Vestfirðir',
        '5': 'Norðurland vestra',
        '6': 'Norðurland eystra',
        '7': 'Austurland',
        '8': 'Suðurland',
    },
    'IN': {
        'AN': 'Andaman and Nicobar Islands',
        'CH': 'Chandigarh',
        'DH': 'Dadra & Nagar Haveli and Daman & Diu',
        'DL': 'Delhi (National Capital Territory)',
        'JK': 'Jammu and Kashmir',
        'LA': 'Ladakh',
        'LD': 'Lakshadweep',
        'PY': 'Puducherry (Pondicherry)',
        'AP': 'Andhra Pradesh',
        'AR': 'Arunachal Pradesh',
        'AS': 'Assam',
        'BR': 'Bihar',
        'CT': 'Chhattisgarh',
        'GA': 'Goa',
        'GJ': 'Gujarat',
        'HR': 'Haryana',
        'HP': 'Himachal Pradesh',
        'JH': 'Jharkhand',
        'KA': 'Karnataka',
        'KL': 'Kerala',
        'MP': 'Madhya Pradesh',
        'MH': 'Maharashtra',
        'MN': 'Manipur',
        'ML': 'Meghalaya',
        'MZ': 'Mizoram',
        'NL': 'Nagaland',
        'OR': 'Odisha (Orissa)',
        'PB': 'Punjab',
        'RJ': 'Rajasthan',
        'SK': 'Sikkim',
        'TN': 'Tamil Nadu',
        'TG': 'Telangana',
        'TR': 'Tripura',
        'UP': 'Uttar Pradesh',
        'UT': 'Uttarakhand',
        'WB': 'West Bengal',
    },
    'ID': {
        'AC': 'Aceh',
        'BA': 'Bali',
        'BB': 'Kepulauan Bangka Belitung',
        'BE': 'Bengkulu',
        'BT': 'Banten',
        'GO': 'Gorontalo',
        'JA': 'Jambi',
        'JB': 'Jawa Barat',
        'JI': 'Jawa Timur',
        'JK': 'Jakarta (Daerah Khusus Ibukota)',
        'JT': 'Jawa Tengah',
        'KA': 'Kalimantan Utara',
        'KB': 'Kalimantan Barat',
        'KI': 'Kalimantan Timur',
        'KR': 'Kepulauan Riau',
        'KS': 'Kalimantan Selatan',
        'KT': 'Kalimantan Tengah',
        'LA': 'Lampung',
        'MA': 'Maluku',
        'MU': 'Maluku Utara',
        'NB': 'Nusa Tenggara Barat',
        'NT': 'Nusa Tenggara Timur',
        'PA': 'Papua',
        'PB': 'Papua Barat',
        'PL': 'Sulawesi Barat',
        'PM': 'Papua Tengah (new province, 2022*)',
        'PS': 'Papua Selatan (new province, 2022*)',
        'PT': 'Papua Pegunungan (new province, 2022*)',
        'RI': 'Riau',
        'SA': 'Sulawesi Utara',
        'SB': 'Sumatera Barat',
        'SN': 'Sulawesi Selatan',
        'SR': 'Sulawesi Tenggara',
        'SS': 'Sumatera Selatan',
        'ST': 'Sulawesi Tengah',
        'SU': 'Sumatera Utara',
        'YO': 'Yogyakarta (Daerah Istimewa Yogyakarta)',
    },
    'IQ': {
        'AN': 'Al Anbar',
        'AR': 'Arbīl (Erbil)',
        'BA': 'Al Basrah',
        'BB': 'Bābil (Babil)',
        'BG': 'Baghdād (Baghdad)',
        'DA': 'Dahūk (Dohuk)',
        'DI': 'Diyālá (Diyala)',
        'DQ': 'Dhī Qār (Dhi Qar)',
        'KA': 'Karbalā’ (Karbala)',
        'KI': 'Kirkūk (Kirkuk)',
        'MA': 'Maysān (Maysan)',
        'MU': 'Al Muthanná',
        'NA': 'An Najaf',
        'NI': 'Nīnawá (Nineveh)',
        'QA': 'Al Qādisiyyah',
        'SD': 'Şalāḩ ad Dīn (Salah al-Din)',
        'SU': 'As Sulaymānīyah (Sulaimani)',
        'TH': 'At Taʼmīm (older code for Kirkuk)',
        'WA': 'Wāsiţ (Wasit)',
    },
    'IE': {
        'CW': 'Carlow',
        'CN': 'Cavan',
        'CE': 'Clare',
        'CO': 'Cork',
        'DL': 'Donegal',
        'D': 'Dublin',
        'G': 'Galway',
        'KY': 'Kerry',
        'KE': 'Kildare',
        'KK': 'Kilkenny',
        'LS': 'Laois',
        'LM': 'Leitrim',
        'LK': 'Limerick',
        'LD': 'Longford',
        'LH': 'Louth',
        'MO': 'Mayo',
        'MH': 'Meath',
        'MN': 'Monaghan',
        'OY': 'Offaly',
        'RN': 'Roscommon',
        'SO': 'Sligo',
        'TA': 'Tipperary',
        'WD': 'Waterford',
        'WH': 'Westmeath',
        'WX': 'Wexford',
        'WW': 'Wicklow',
    },
    'IM': {
        'IM': 'Isle of Man',
    },
    'IL': {
        'D': 'HaDarom (Southern)',
        'HA': 'Haifa',
        'JM': 'Yerushalayim (Jerusalem)',
        'M': 'HaMerkaz (Central)',
        'TA': 'Tel-Aviv',
        'Z': 'HaZafon (Northern)',
        'WB': 'Judea and Samaria (West Bank)',
    },
    'IT': {
        '21': 'Piemonte',
        '23': 'Valle d’Aosta',
        '25': 'Lombardia',
        '32': 'Trentino-Alto Adige',
        '34': 'Veneto',
        '36': 'Friuli-Venezia Giulia',
        '42': 'Liguria',
        '45': 'Emilia-Romagna',
        '52': 'Toscana',
        '55': 'Umbria',
        '57': 'Marche',
        '62': 'Lazio',
        '65': 'Abruzzo',
        '67': 'Molise',
        '72': 'Campania',
        '75': 'Puglia',
        '77': 'Basilicata',
        '78': 'Calabria',
        '82': 'Sicilia',
        '88': 'Sardegna',
    },
    'JM': {
        '01': 'Kingston',
        '02': 'Saint Andrew',
        '03': 'Saint Thomas',
        '04': 'Portland',
        '05': 'Saint Mary',
        '06': 'Saint Ann',
        '07': 'Trelawny',
        '08': 'Saint James',
        '09': 'Hanover',
        '10': 'Westmoreland',
        '11': 'Saint Elizabeth',
        '12': 'Manchester',
        '13': 'Clarendon',
        '14': 'Saint Catherine',
    },
    'JP': {
        '01': 'Hokkaidō',
        '02': 'Aomori',
        '03': 'Iwate',
        '04': 'Miyagi',
        '05': 'Akita',
        '06': 'Yamagata',
        '07': 'Fukushima',
        '08': 'Ibaraki',
        '09': 'Tochigi',
        '10': 'Gunma',
        '11': 'Saitama',
        '12': 'Chiba',
        '13': 'Tōkyō',
        '14': 'Kanagawa',
        '15': 'Niigata',
        '16': 'Toyama',
        '17': 'Ishikawa',
        '18': 'Fukui',
        '19': 'Yamanashi',
        '20': 'Nagano',
        '21': 'Gifu',
        '22': 'Shizuoka',
        '23': 'Aichi',
        '24': 'Mie',
        '25': 'Shiga',
        '26': 'Kyōto',
        '27': 'Ōsaka',
        '28': 'Hyōgo',
        '29': 'Nara',
        '30': 'Wakayama',
        '31': 'Tottori',
        '32': 'Shimane',
        '33': 'Okayama',
        '34': 'Hiroshima',
        '35': 'Yamaguchi',
        '36': 'Tokushima',
        '37': 'Kagawa',
        '38': 'Ehime',
        '39': 'Kōchi',
        '40': 'Fukuoka',
        '41': 'Saga',
        '42': 'Nagasaki',
        '43': 'Kumamoto',
        '44': 'Ōita',
        '45': 'Miyazaki',
        '46': 'Kagoshima',
        '47': 'Okinawa',
    },
    'JE': {
        'J': 'Jersey',
    },
    'JO': {
        'AJ': '‘Ajlūn',
        'AM': 'Al ‘Aqabah',
        'AQ': 'Al ‘Aqaba (older variation of code AM)',
        'BA': 'Al Balqā’',
        'IR': 'Irbid',
        'JA': 'Jarash',
        'KA': 'Al Karak',
        'MA': 'Al Mafraq',
        'MD': 'Mādabā',
        'MN': 'Ma‘ān',
        'AQ2': 'Aqaba (possible legacy code usage)',
        'AZ': 'Az Zarqā’',
        'TA': 'Aţ Ţafīlah',
    },
    'KZ': {
        'AKM': 'Akmola',
        'AKT': 'Aktobe',
        'ALA': 'Almaty (city)',
        'ALM': 'Almaty (region)',
        'AMT': 'Zhetysu (new region from Almaty region, 2022)*',
        'AST': 'Astana (city, formerly Nur-Sultan)',
        'ATY': 'Atyrau',
        'BAY': 'Baykonyr (city within Kyzylorda?)**',
        'KAR': 'Karaganda',
        'KUS': 'Ulytau (new region from Karaganda, 2022)*',
        'KZY': 'Kyzylorda',
        'MAN': 'Mangystau',
        'PAV': 'Pavlodar',
        'SEV': 'North Kazakhstan',
        'SHM': 'Shymkent (city)',
        'VOS': 'East Kazakhstan',
        'YUZ': 'Turkistan (new region formerly South Kazakhstan)',
        'ZAP': 'West Kazakhstan',
        'ZHA': 'Zhambyl',
    },
    'KE': {
        '01': 'Baringo',
        '02': 'Bomet',
        '03': 'Bungoma',
        '04': 'Busia',
        '05': 'Elgeyo/Marakwet',
        '06': 'Embu',
        '07': 'Garissa',
        '08': 'Homa Bay',
        '09': 'Isiolo',
        '10': 'Kajiado',
        '11': 'Kakamega',
        '12': 'Kericho',
        '13': 'Kiambu',
        '14': 'Kilifi',
        '15': 'Kirinyaga',
        '16': 'Kisii',
        '17': 'Kisumu',
        '18': 'Kitui',
        '19': 'Kwale',
        '20': 'Laikipia',
        '21': 'Lamu',
        '22': 'Machakos',
        '23': 'Makueni',
        '24': 'Mandera',
        '25': 'Marsabit',
        '26': 'Meru',
        '27': 'Migori',
        '28': 'Mombasa',
        '29': 'Murang’a',
        '30': 'Nairobi City',
        '31': 'Nakuru',
        '32': 'Nandi',
        '33': 'Narok',
        '34': 'Nyamira',
        '35': 'Nyandarua',
        '36': 'Nyeri',
        '37': 'Samburu',
        '38': 'Siaya',
        '39': 'Taita–Taveta',
        '40': 'Tana River',
        '41': 'Tharaka-Nithi',
        '42': 'Trans Nzoia',
        '43': 'Turkana',
        '44': 'Uasin Gishu',
        '45': 'Vihiga',
        '46': 'Wajir',
        '47': 'West Pokot',
    },
    'KI': {
        'K': 'Kiribati',
    },
    'KR': {
        '11': 'Seoul (Teukbyeolsi)',
        '26': 'Busan (Gwangyeoksi)',
        '27': 'Daegu (Gwangyeoksi)',
        '28': 'Incheon (Gwangyeoksi)',
        '29': 'Gwangju (Gwangyeoksi)',
        '30': 'Daejeon (Gwangyeoksi)',
        '31': 'Ulsan (Gwangyeoksi)',
        '36': 'Sejong (Teukbyeol Jachisi)',
        '41': 'Gyeonggi-do',
        '42': 'Gangwon-do',
        '43': 'Chungcheongbuk-do',
        '44': 'Chungcheongnam-do',
        '45': 'Jeollabuk-do',
        '46': 'Jeollanam-do',
        '47': 'Gyeongsangbuk-do',
        '48': 'Gyeongsangnam-do',
        '49': 'Jeju (Jeju Special Self-Governing Province)',
    },
    'KW': {
        'AH': 'Al Aḩmadī',
        'FA': 'Al Farwānīyah',
        'JA': 'Al Jahrrā’',
        'KU': 'Al Kuwayt (Capital)',
        'HA': 'Ḩawallī',
        'MU': 'Mubārak al Kabīr',
    },
    'KG': {
        'B': 'Batken',
        'C': 'Chüy',
        'GB': 'Bishkek (city)',
        'GO': 'Osh (city)',
        'J': 'Jalal-Abad',
        'N': 'Naryn',
        'O': 'Osh (region)',
        'T': 'Talas',
        'Y': 'Issyk-Kul (Ysyk-Köl)',
    },
    'LA': {
        'AT': 'Attapu',
        'BK': 'Bokèo',
        'BL': 'Bolikhamxai',
        'CH': 'Champasak',
        'HO': 'Houaphan',
        'KH': 'Khammouan',
        'LM': 'Louang Namtha',
        'LP': 'Louangphabang',
        'OU': 'Oudômxai',
        'PH': 'Phôngsali',
        'SL': 'Salavan',
        'SV': 'Savannakhét',
        'VI': 'Vientiane (prefecture)',
        'VT': 'Vientiane (province)',
        'XA': 'Xaignabouri (Sainyabuli)',
        'XE': 'Xékong',
        'XI': 'Xiangkhouang',
        'XS': 'Xaisomboun',
    },
    'LV': {
        '001': 'Rīga (City)',
        '002': 'Pierīga',
        '003': 'Vidzeme',
        '004': 'Kurzeme',
        '005': 'Zemgale',
        '006': 'Latgale',
    },
    'LB': {
        'AK': 'Akkar',
        'AS': 'North (Ash Shamal)',
        'BA': 'Beirut (Bayrūt)',
        'BH': 'Baalbek-Hermel',
        'BI': 'Beqaa (Al Biqa‘)',
        'JA': 'South (Al Janub)',
        'JL': 'Mount Lebanon (Jabal Lubnān)',
        'NA': 'Nabatieh (An Nabatiyah)',
    },
    'LS': {
        'A': 'Butha-Buthe',
        'B': 'Leribe',
        'C': 'Berea',
        'D': 'Maseru',
        'E': 'Mafeteng',
        'F': 'Mohale’s Hoek',
        'G': 'Quthing',
        'H': 'Qacha’s Nek',
        'J': 'Mokhotlong',
        'K': 'Thaba-Tseka',
    },
    'LR': {
        'BG': 'Bong',
        'BM': 'Bomi',
        'CM': 'Grand Cape Mount',
        'GB': 'Grand Bassa',
        'GG': 'Gbarpolu',
        'GK': 'Grand Kru',
        'GM': 'Grand Gedeh',
        'LO': 'Lofa',
        'MG': 'Margibi',
        'MO': 'Montserrado',
        'MY': 'Maryland',
        'NI': 'Nimba',
        'RV': 'Rivercess',
        'RG': 'River Gee',
        'SN': 'Sinoe',
    },
    'LY': {
        'BA': 'Benghazi',
        'BU': 'Butnan',
        'DR': 'Derna',
        'GT': 'Ghat',
        'JA': 'Jabal al Akhdar',
        'JB': 'Jabal al Gharbi',
        'JG': 'Jafara',
        'JI': 'Jufra',
        'JU': 'Murzuq',
        'KF': 'Kufra',
        'MB': 'Mbardi (possibly older code?)',
        'MI': 'Misrata',
        'MJ': 'Marj',
        'MQ': 'Murqub',
        'NL': 'Nalut',
        'SB': 'Sabha',
        'SR': 'Sirte',
        'TB': 'Tripoli',
        'WA': 'Wadi al Hayaa',
        'WQ': 'Wadi ash Shatii',
        'ZA': 'Zawiya',
        'ZW': 'Zwila (disputed older code?)',
    },
    'LI': {
        'L': 'Liechtenstein',
    },
    'LT': {
        'AL': 'Alytaus',
        'KL': 'Klaipėdos',
        'KU': 'Kauno',
        'MR': 'Marijampolės',
        'PN': 'Panevėžio',
        'SA': 'Šiaulių',
        'TA': 'Tauragės',
        'TE': 'Telšių',
        'UT': 'Utenos',
        'VI': 'Vilniaus',
    },
    'LU': {
        'CA': 'Capellen',
        'CL': 'Clervaux',
        'DI': 'Diekirch',
        'EC': 'Echternach',
        'ES': 'Esch-sur-Alzette',
        'GR': 'Grevenmacher',
        'LU': 'Luxembourg (canton)',
        'ME': 'Mersch',
        'RD': 'Redange',
        'RM': 'Remich',
        'VD': 'Vianden',
        'WI': 'Wiltz',
    },
    'MO': {
        'M': 'Macao SAR',
    },
    'MG': {
        'A': 'Toamasina',
        'D': 'Antsiranana',
        'F': 'Fianarantsoa',
        'M': 'Mahajanga',
        'T': 'Antananarivo',
        'U': 'Toliara',
    },
    'MW': {
        'N': 'Northern Region',
        'C': 'Central Region',
        'S': 'Southern Region',
    },
    'MY': {
        '01': 'Johor',
        '02': 'Kedah',
        '03': 'Kelantan',
        '04': 'Melaka (Malacca)',
        '05': 'Negeri Sembilan',
        '06': 'Pahang',
        '07': 'Pulau Pinang (Penang)',
        '08': 'Perak',
        '09': 'Perlis',
        '10': 'Selangor',
        '11': 'Terengganu',
        '12': 'Sabah',
        '13': 'Sarawak',
        '14': 'Kuala Lumpur',
        '15': 'Labuan',
        '16': 'Putrajaya',
    },
    'MV': {
        '00': 'Malé',
        '01': 'Addu City (Seenu)',
        '02': 'Faafu',
        '03': 'Gaafu Alif',
        '04': 'Gaafu Dhaalu',
        '05': 'Gnaviyani',
        '07': 'Haa Alif',
        '08': 'Haa Dhaalu',
        '12': 'Laamu',
        '13': 'Lhaviyani',
        '14': 'Meemu',
        '17': 'Noonu',
        '20': 'Raa',
        '23': 'Shaviyani',
        '24': 'Thaa',
        '25': 'Vaavu',
        '27': 'Kaafu',
        '28': 'Alif Alif',
        '29': 'Alif Dhaalu',
        '31': 'Baa',
        '32': 'Dhaalu',

    },
    'ML': {
        'BKO': 'Bamako (Capital District)',
        '1': 'Kayes',
        '2': 'Koulikoro',
        '3': 'Sikasso',
        '4': 'Ségou',
        '5': 'Mopti',
        '6': 'Tombouctou',
        '7': 'Gao',
        '8': 'Kidal',
        '9': 'Taoudénit',
        '10': 'Ménaka',
    },
    'MT': {
        'M': 'Malta',
    },
    'MH': {
        'MI': 'Marshall Islands',
    },
    'MQ': {
        'M': 'Martinique',
    },
    'MR': {
        '01': 'Hodh ech Chargui',
        '02': 'Hodh el Gharbi',
        '03': 'Assaba',
        '04': 'Gorgol',
        '05': 'Brakna',
        '06': 'Trarza',
        '07': 'Adrar',
        '08': 'Dakhlet Nouadhibou',
        '09': 'Tagant',
        '10': 'Guidimaka',
        '11': 'Tiris Zemmour',
        '12': 'Inchiri',
        '13': 'Nouakchott Ouest',
        '14': 'Nouakchott Nord',
        '15': 'Nouakchott Sud',
    },
    'MU': {
        'AG': 'Agalega Islands',
        'BL': 'Black River',
        'CC': 'Cargados Carajos Shoals (Saint Brandon)',
        'FL': 'Flacq',
        'GP': 'Grand Port',
        'MO': 'Moka',
        'PA': 'Pamplemousses',
        'PL': 'Port Louis',
        'PW': 'Plaines Wilhems',
        'QB': 'Quatre Bornes (sometimes used as local authority)',
        'RR': 'Rivière du Rempart',
        'SA': 'Savanne',
        'VP': 'Vacoas-Phoenix (sometimes local authority)',
    },
    'YT': {
        'M': 'Mayotte',
    },
    'MX': {
        'AGU': 'Aguascalientes',
        'BCN': 'Baja California',
        'BCS': 'Baja California Sur',
        'CAM': 'Campeche',
        'CHP': 'Chiapas',
        'CHH': 'Chihuahua',
        'CMX': 'Ciudad de México (Mexico City)',
        'COA': 'Coahuila de Zaragoza',
        'COL': 'Colima',
        'DUR': 'Durango',
        'GUA': 'Guanajuato',
        'GRO': 'Guerrero',
        'HID': 'Hidalgo',
        'JAL': 'Jalisco',
        'MEX': 'México (State of Mexico)',
        'MIC': 'Michoacán de Ocampo',
        'MOR': 'Morelos',
        'NAY': 'Nayarit',
        'NLE': 'Nuevo León',
        'OAX': 'Oaxaca',
        'PUE': 'Puebla',
        'QUE': 'Querétaro',
        'ROO': 'Quintana Roo',
        'SLP': 'San Luis Potosí',
        'SIN': 'Sinaloa',
        'SON': 'Sonora',
        'TAB': 'Tabasco',
        'TAM': 'Tamaulipas',
        'TLA': 'Tlaxcala',
        'VER': 'Veracruz de Ignacio de la Llave',
        'YUC': 'Yucatán',
        'ZAC': 'Zacatecas',
    },
    'FM': {
        'KSA': 'Kosrae',
        'PNI': 'Pohnpei',
        'CHK': 'Chuuk',
        'YAP': 'Yap',
    },
    'MD': {
        'AN': 'Anenii Noi',
        'BA': 'Basarabeasca',
        'BD': 'Tighina (Bender, Municipality)',
        'BR': 'Briceni',
        'BS': 'Bălți (Municipality)',
        'CA': 'Cahul',
        'CL': 'Călărași',
        'CM': 'Cimișlia',
        'CR': 'Criuleni',
        'CS': 'Chișinău (Municipality)',
        'CT': 'Cantemir',
        'CU': 'Chișinău (older code?), check duplicates',
        'DO': 'Dondușeni',
        'DR': 'Drochia',
        'ED': 'Edineț',
        'FA': 'Fălești',
        'FL': 'Florești',
        'GA': 'Găgăuzia (Autonomous Territorial Unit)',
        'GL': 'Glodeni',
        'HI': 'Hîncești',
        'IA': 'Ialoveni',
        'LE': 'Leova',
        'NI': 'Nisporeni',
        'OC': 'Ocnița',
        'OR': 'Orhei',
        'RE': 'Rezina',
        'RI': 'Rîșcani',
        'SI': 'Sîngerei',
        'SO': 'Soroca',
        'ST': 'Strășeni',
        'SV': 'Șoldănești',
        'TA': 'Taraclia',
        'TE': 'Telenești',
        'UN': 'Ungheni',
        'SD': 'Stânga Nistrului (Transnistria, disputed)',
    },
    'MC': {
        'M': 'Monaco',
    },
    'MN': {
        '1': 'Ulaanbaatar (municipality)',
        '035': 'Orhon',
        '037': 'Darhan uul',
        '039': 'Hentiy',
        '041': 'Hövsgöl',
        '043': 'Hovd',
        '046': 'Uvs',
        '047': 'Töv',
        '049': 'Selenge',
        '051': 'Sühbaatar',
        '053': 'Ömnögovi',
        '055': 'Övörhangay',
        '057': 'Dzavhan',
        '059': 'Dundgovi',
        '061': 'Dornod',
        '063': 'Dornogovi',
        '064': 'Govi-Sumber',
        '065': 'Govi-Altay',
        '067': 'Bulgan',
        '069': 'Bayanhongor',
        '071': 'Bayan-Ölgiy',
        '073': 'Arkhangai',
    },
    'ME': {
        '01': 'Andrijevica',
        '02': 'Bar',
        '03': 'Berane',
        '04': 'Bijelo Polje',
        '05': 'Budva',
        '06': 'Cetinje',
        '07': 'Danilovgrad',
        '08': 'Gusinje',
        '09': 'Herceg Novi',
        '10': 'Kolašin',
        '11': 'Kotor',
        '12': 'Mojkovac',
        '13': 'Nikšić',
        '14': 'Petnjica',
        '15': 'Plav',
        '16': 'Pljevlja',
        '17': 'Plužine',
        '18': 'Podgorica',
        '19': 'Rožaje',
        '20': 'Šavnik',
        '21': 'Tivat',
        '22': 'Ulcinj',
        '23': 'Žabljak',
        '24': 'Tuzi (new municipality)',
    },
    'MS': {
        'M': 'Montserrat',
    },
    'MA': {
        '01': 'Tanger-Tétouan-Al Hoceïma',
        '02': 'L’Oriental',
        '03': 'Fès-Meknès',
        '04': 'Rabat-Salé-Kénitra',
        '05': 'Béni Mellal-Khénifra',
        '06': 'Casablanca-Settat',
        '07': 'Marrakech-Safi',
        '08': 'Drâa-Tafilalet',
        '09': 'Souss-Massa',
        '10': 'Guelmim-Oued Noun',
        '11': 'Laâyoune-Sakia El Hamra',
        '12': 'Dakhla-Oued Ed-Dahab',
    },
    'MZ': {
        'A': 'Niassa',
        'B': 'Manica',
        'G': 'Gaza',
        'I': 'Inhambane',
        'L': 'Maputo (province)',
        'MPM': 'Maputo (city)',
        'N': 'Nampula',
        'P': 'Cabo Delgado',
        'Q': 'Zambézia',
        'S': 'Sofala',
        'T': 'Tete',
    },
    'MM': {
        '01': 'Sagaing',
        '02': 'Bago',
        '03': 'Magway',
        '04': 'Mandalay',
        '05': 'Tanintharyi',
        '06': 'Yangon',
        '07': 'Ayeyarwady',
        '11': 'Kachin',
        '12': 'Kayah',
        '13': 'Kayin',
        '14': 'Chin',
        '15': 'Mon',
        '16': 'Rakhine',
        '17': 'Shan',
        '18': 'Naypyidaw (Union Territory)',
    },
    'NA': {
        'CA': 'Zambezi (formerly Caprivi)',
        'ER': 'Erongo',
        'HA': 'Hardap',
        'KA': 'Karas (now ǁKaras)',
        'KH': 'Khomas',
        'KU': 'Kunene',
        'KW': 'Kavango West',
        'KE': 'Kavango East',
        'OH': 'Ohangwena',
        'OK': 'Oshikoto',
        'OM': 'Oshana',
        'ON': 'Omaheke',
        'OS': 'Omusati',
        'OT': 'Otjozondjupa',
    },
    'NR': {
        'N': 'Nauru',
    },
    'NP': {
        'P1': 'Province 1',
        'P2': 'Madhesh Province',
        'P3': 'Bagmati Province',
        'P4': 'Gandaki Province',
        'P5': 'Lumbini Province',
        'P6': 'Karnali Province',
        'P7': 'Sudurpashchim Province',
    },
    'NL': {
        'DR': 'Drenthe',
        'FL': 'Flevoland',
        'FR': 'Fryslân',
        'GE': 'Gelderland',
        'GR': 'Groningen',
        'LI': 'Limburg',
        'NB': 'Noord-Brabant',
        'NH': 'Noord-Holland',
        'OV': 'Overijssel',
        'UT': 'Utrecht',
        'ZE': 'Zeeland',
        'ZH': 'Zuid-Holland',
    },
    'NC': {
        'NC': 'New Caledonia',
    },
    'NZ': {
        'AUK': 'Auckland',
        'BOP': 'Bay of Plenty',
        'CAN': 'Canterbury',
        'CIT': 'Chatham Islands Territory',
        'GIS': 'Gisborne',
        'HKB': 'Hawke’s Bay',
        'MWT': 'Manawatu-Wanganui',
        'MBH': 'Marlborough',
        'NSN': 'Nelson',
        'NTL': 'Northland',
        'OTA': 'Otago',
        'STL': 'Southland',
        'TAS': 'Tasman',
        'TKI': 'Taranaki',
        'WGN': 'Wellington',
        'WKO': 'Waikato',
        'WTC': 'West Coast',
    },
    'NI': {
        'AN': 'Atlántico Norte (RAAN, now Norte)',
        'AS': 'Atlántico Sur (RAAS, now Sur)',
        'BO': 'Boaco',
        'CA': 'Carazo',
        'CI': 'Chinandega',
        'CO': 'Chontales',
        'ES': 'Estelí',
        'GR': 'Granada',
        'JI': 'Jinotega',
        'LE': 'León',
        'MD': 'Madriz',
        'MN': 'Managua',
        'MS': 'Masaya',
        'MT': 'Matagalpa',
        'NS': 'Nueva Segovia',
        'RI': 'Rivas',
        'SC': 'Río San Juan (San Carlos in some references)',
    },
    'NE': {
        '1': 'Agadez',
        '2': 'Diffa',
        '3': 'Dosso',
        '4': 'Maradi',
        '5': 'Tahoua',
        '6': 'Tillabéri',
        '7': 'Zinder',
        '8': 'Niamey (Capital District)',
    },
    'NG': {
        'AB': 'Abia',
        'AD': 'Adamawa',
        'AK': 'Akwa Ibom',
        'AN': 'Anambra',
        'BA': 'Bauchi',
        'BE': 'Benue',
        'BO': 'Borno',
        'BY': 'Bayelsa',
        'CR': 'Cross River',
        'DE': 'Delta',
        'EB': 'Ebonyi',
        'ED': 'Edo',
        'EK': 'Ekiti',
        'EN': 'Enugu',
        'FC': 'Federal Capital Territory (Abuja)',
        'GO': 'Gombe',
        'IM': 'Imo',
        'JI': 'Jigawa',
        'KD': 'Kaduna',
        'KE': 'Kebbi',
        'KN': 'Kano',
        'KO': 'Kogi',
        'KT': 'Katsina',
        'KW': 'Kwara',
        'LA': 'Lagos',
        'NA': 'Nasarawa',
        'NI': 'Niger',
        'OG': 'Ogun',
        'ON': 'Ondo',
        'OS': 'Osun',
        'OY': 'Oyo',
        'PL': 'Plateau',
        'RI': 'Rivers',
        'SO': 'Sokoto',
        'TA': 'Taraba',
        'YO': 'Yobe',
        'ZA': 'Zamfara',
    },
    'NU': {
        'N': 'Niue',
    },
    'NF': {
        'NI': 'Norfolk Island',
    },
    'MK': {
        '01': 'Aerodrom',
        '02': 'Aračinovo',
        '03': 'Berovo',
        '04': 'Bitola',
        '05': 'Bogdanci',
        'SK': 'Skopje (City)',
    },
    'MP': {
        'NI': 'Northern Mariana Islands',
    },
    'NO': {
        '01': 'Østfold (merged into Viken in 2020)',
        '02': 'Akershus (merged into Viken)',
        '03': 'Oslo',
        '04': 'Hedmark (merged into Innlandet)',
        '05': 'Oppland (merged into Innlandet)',
        '06': 'Buskerud (merged into Viken)',
        '07': 'Vestfold (merged into Vestfold og Telemark)',
        '08': 'Telemark (merged into Vestfold og Telemark)',
        '09': 'Aust-Agder (merged into Agder)',
        '10': 'Vest-Agder (merged into Agder)',
        '11': 'Rogaland',
        '12': 'Hordaland (merged into Vestland)',
        '14': 'Sogn og Fjordane (merged into Vestland)',
        '15': 'Møre og Romsdal',
        '18': 'Nordland',
        '19': 'Troms (merged into Troms og Finnmark)',
        '20': 'Finnmark (merged into Troms og Finnmark)',
        '30': 'Viken',
        '34': 'Innlandet',
        '38': 'Vestfold og Telemark',
        '42': 'Agder',
        '46': 'Vestland',
        '50': 'Trøndelag',
        '54': 'Troms og Finnmark',
    },
    'OM': {
        'BS': 'Busaid',
        'BJ': 'Al Batinah North ',
        'BK': 'Al Batinah South',
        'BU': 'Al Buraymi',
        'DA': 'Ad Dakhiliyah',
        'MA': 'Muscat',
        'MU': 'Musandam',
        'SH': 'Ash Sharqiyah North',
        'SS': 'Ash Sharqiyah South',
        'WU': 'Al Wusta',
        'ZA': 'Az̧ Z̧āhirah',
        'ZU': 'Adh Dhahirah ',
        'ZA2': 'Ad Dhahirah',
        'ZA3': 'Dhofar',
    },
    'PK': {
        'BA': 'Balochistan',
        'IS': 'Islamabad Capital Territory',
        'JK': 'Azad Jammu and Kashmir',
        'KP': 'Khyber Pakhtunkhwa',
        'PB': 'Punjab',
        'SD': 'Sindh',
        'GB': 'Gilgit-Baltistan',
        'TA': 'Federally Administered Tribal Areas',
    },
    'PW': {
        'P': 'Palau',
    },
    'PS': {
        'BTH': 'Bethlehem',
        'DEB': 'Deir al-Balah',
        'GZA': 'Gaza',
        'HBN': 'Hebron (Al Khalil)',
        'JEM': 'Jerusalem (Al Quds)',
        'JEN': 'Jenin',
        'JRH': 'Jericho (Ariha)',
        'KYS': 'Khan Yunis',
        'NBS': 'Nablus',
        'NGZ': 'North Gaza',
        'QQA': 'Qalqilya',
        'RBH': 'Ramallah and Al-Bireh',
        'RFH': 'Rafah',
        'SLT': 'Salfit',
        'TBS': 'Tubas',
        'TQM': 'Tulkarm',
    },
    'PA': {
        '1': 'Bocas del Toro',
        '2': 'Coclé',
        '3': 'Colón',
        '4': 'Chiriquí',
        '5': 'Darién',
        '6': 'Herrera',
        '7': 'Los Santos',
        '8': 'Panamá',
        '9': 'Veraguas',
        '10': 'Panamá Oeste',

        'EM': 'Emberá (Comarca)',
        'KY': 'Guna Yala (Comarca)',
        'NB': 'Ngäbe-Buglé (Comarca)',
        'SB': 'Wargandí / Madugandí? (Details vary, often not in ISO yet)',
    },
    'PG': {
        'CPK': 'Chimbu (Simbu)',
        'CPM': 'Central',
        'EBR': 'East New Britain',
        'EHG': 'Eastern Highlands',
        'EPW': 'Enga',
        'GPK': 'Gulf',
        'HLA': 'Hela',
        'JWK': 'Jiwaka',
        'MBA': 'Milne Bay',
        'MPL': 'Morobe',
        'MPM': 'Madang',
        'MRL': 'Manus',
        'NCD': 'National Capital District (Port Moresby)',
        'NIK': 'New Ireland',
        'NPP': 'Northern (Oro)',
        'NSB': 'Bougainville (Autonomous Region)',
        'SAN': 'West Sepik (Sandaun)',
        'SHM': 'Southern Highlands',
        'WBK': 'West New Britain',
        'WHM': 'Western Highlands',
        'WPD': 'Western (Fly)',
        'EPG': 'East Sepik',
        'SIM': 'Simbu? (duplicate code for CPK, be careful)',
    },
    'PY': {
        '1': 'Concepción',
        '2': 'San Pedro',
        '3': 'Cordillera',
        '4': 'Guairá',
        '5': 'Caaguazú',
        '6': 'Caazapá',
        '7': 'Itapúa',
        '8': 'Misiones',
        '9': 'Paraguarí',
        '10': 'Alto Paraná',
        '11': 'Central',
        '12': 'Ñeembucú',
        '13': 'Amambay',
        '14': 'Canindeyú',
        '15': 'Presidente Hayes',
        '16': 'Alto Paraguay',
        '19': 'Boquerón',
        'ASU': 'Asunción (capital district)',
    },
    'PE': {
        'AMA': 'Amazonas',
        'ANC': 'Ancash',
        'APU': 'Apurímac',
        'ARE': 'Arequipa',
        'AYA': 'Ayacucho',
        'CAJ': 'Cajamarca',
        'CAL': 'El Callao (constitutional province)',
        'CUS': 'Cusco',
        'HUV': 'Huancavelica',
        'HUC': 'Huánuco',
        'ICA': 'Ica',
        'JUN': 'Junín',
        'LAL': 'La Libertad',
        'LAM': 'Lambayeque',
        'LIM': 'Lima (region)',
        'LMA': 'Municipalidad Metropolitana de Lima (provincial municipality)',
        'LOR': 'Loreto',
        'MDD': 'Madre de Dios',
        'MOQ': 'Moquegua',
        'PAS': 'Pasco',
        'PIU': 'Piura',
        'PUN': 'Puno',
        'SAM': 'San Martín',
        'TAC': 'Tacna',
        'TUM': 'Tumbes',
        'UCA': 'Ucayali',
    },
    'PH': {
        '14': 'Autonomous Region in Muslim Mindanao (old code, replaced by BARMM)',
        'BARMM': 'Bangsamoro Autonomous Region in Muslim Mindanao',
        'CAR': 'Cordillera Administrative Region',
        'NCR': 'National Capital Region (Metro Manila)',
        '01': 'Ilocos Region (Region I)',
        '02': 'Cagayan Valley (Region II)',
        '03': 'Central Luzon (Region III)',
        '04': 'CALABARZON (Region IV-A)',
        '05': 'Bicol Region (Region V)',
        '06': 'Western Visayas (Region VI)',
        '07': 'Central Visayas (Region VII)',
        '08': 'Eastern Visayas (Region VIII)',
        '09': 'Zamboanga Peninsula (Region IX)',
        '10': 'Northern Mindanao (Region X)',
        '11': 'Davao Region (Region XI)',
        '12': 'SOCCSKSARGEN (Region XII)',
        '13': 'Caraga (Region XIII)',
    },
    'PN': {
        'PI': 'Pitcairn Islands',
    },
    'PL': {
        'DS': 'Dolnośląskie',
        'KP': 'Kujawsko-Pomorskie',
        'LU': 'Lubelskie',
        'LB': 'Lubuskie',
        'LD': 'Łódzkie',
        'MA': 'Małopolskie',
        'MZ': 'Mazowieckie',
        'OP': 'Opolskie',
        'PK': 'Podkarpackie',
        'PD': 'Podlaskie',
        'PM': 'Pomorskie',
        'SL': 'Śląskie',
        'ŚK': 'Świętokrzyskie (ISO code actually "SK"? Some references show "SW")',
        'WN': 'Warmińsko-Mazurskie (ISO code "PL-WN" or "PL-28" older?)',
        'WP': 'Wielkopolskie',
        'ZP': 'Zachodniopomorskie',
    },
    'PT': {
        '01': 'Aveiro',
        '02': 'Beja',
        '03': 'Braga',
        '04': 'Bragança',
        '05': 'Castelo Branco',
        '06': 'Coimbra',
        '07': 'Évora',
        '08': 'Faro',
        '09': 'Guarda',
        '10': 'Leiria',
        '11': 'Lisboa',
        '12': 'Portalegre',
        '13': 'Porto',
        '14': 'Santarém',
        '15': 'Setúbal',
        '16': 'Viana do Castelo',
        '17': 'Vila Real',
        '18': 'Viseu',
        '20': 'Região Autónoma dos Açores',
        '30': 'Região Autónoma da Madeira',
    },
    'PR': {
        'PR': 'Puerto Rico',
    },
    'QA': {
        'DA': 'Ad Dawhah (Doha)',
        'KH': 'Al Khawr wa adh Dhakhīrah',
        'MS': 'Ash Shamāl',
        'RA': 'Ar Rayyān',
        'WB': 'Al Wakrah',
        'WA': 'Al Wajbah? (older references?), check updates',
        'ZA': 'Az̧ Za‘āyin',
        'US': 'Umm Şalāl',
    },
    'RE': {
        'R': 'Réunion',
    },
    'RO': {
        'AB': 'Alba',
        'AG': 'Argeș',
        'AR': 'Arad',
        'B': 'București (Bucharest)',
        'BC': 'Bacău',
        'BH': 'Bihor',
        'BN': 'Bistrița-Năsăud',
        'BR': 'Brăila',
        'BT': 'Botoșani',
        'BV': 'Brașov',
        'BZ': 'Buzău',
        'CJ': 'Cluj',
        'CL': 'Călărași',
        'CS': 'Caraș-Severin',
        'CT': 'Constanța',
        'CV': 'Covasna',
        'DB': 'Dâmbovița',
        'DJ': 'Dolj',
        'GJ': 'Gorj',
        'GL': 'Galați',
        'GR': 'Giurgiu',
        'HD': 'Hunedoara',
        'HR': 'Harghita',
        'IF': 'Ilfov',
        'IL': 'Ialomița',
        'IS': 'Iași',
        'MH': 'Mehedinți',
        'MM': 'Maramureș',
        'MS': 'Mureș',
        'NT': 'Neamț',
        'OT': 'Olt',
        'PH': 'Prahova',
        'SB': 'Sibiu',
        'SJ': 'Sălaj',
        'SM': 'Satu Mare',
        'SV': 'Suceava',
        'TL': 'Tulcea',
        'TM': 'Timiș',
        'TR': 'Teleorman',
        'VL': 'Vâlcea',
        'VN': 'Vrancea',
        'VS': 'Vaslui',
    },
    'RW': {
        '01': 'City of Kigali',
        '02': 'Eastern Province',
        '03': 'Northern Province',
        '04': 'Western Province',
        '05': 'Southern Province',
    },
    'BL': {
        'SB': 'Saint Barthélemy',
    },
    'SH': {
        'SH': 'Saint Helena, Ascension and Tristan da Cunha',
    },
    'KN': {
        'KN-K': 'Saint Kitts',
        'KN-N': 'Nevis',
    },
    'LC': {
        'SL': 'Saint Lucia',
    },
    'MF': {
        'SM': 'Saint Martin (French part)',
    },
    'PM': {
        'SP': 'Saint Pierre and Miquelon',
    },
    'VC': {
        'SV': 'Saint Vincent and the Grenadines',
    },
    'WS': {
        'S': 'Samoa',
    },
    'SM': {
        'SM': 'San Marino',
    },
    'ST': {
        'ST': 'Sao Tome and Principe',
    },
    'SA': {
        '01': 'Ar Riyāḍ',
        '02': 'Makkah',
        '03': 'Al Madīnah',
        '04': 'Eastern Province (Ash Sharqīyah)',
        '05': 'Al Qaşim',
        '06': 'Ḥāʼil',
        '07': 'Tabūk',
        '08': 'Northern Borders (Al Ḥudūd ash Shamāliyah)',
        '09': 'Jīzān',
        '10': 'Najrān',
        '11': 'Al Bāhah',
        '12': 'Al Jawf',
        '14': '‘Asīr',
    },
    'SN': {
        'DK': 'Dakar',
        'DB': 'Diourbel',
        'FK': 'Fatick',
        'KA': 'Kaffrine',
        'KD': 'Kolda',
        'KE': 'Kédougou',
        'KL': 'Kaolack',
        'LG': 'Louga',
        'ML': 'Mali (older code? Not official in new references)',
        'MT': 'Matam',
        'SL': 'Saint-Louis',
        'SE': 'Sédhiou',
        'TC': 'Tambacounda',
        'TH': 'Thiès',
        'ZG': 'Ziguinchor',
    },
    'RS': {
        '00': 'Belgrade (Beograd)',
        '01': 'North Bačka',
        '02': 'Central Banat',
        '03': 'North Banat',
        '04': 'South Banat',
        '05': 'West Bačka',
        '06': 'South Bačka',
        '07': 'Srem',
        '08': 'Mačva',
        '09': 'Kolubara',
        '10': 'Podunavlje',
        '11': 'Braničevo',
        '12': 'Šumadija',
        '13': 'Pomoravlje',
        '14': 'Bor',
        '15': 'Zaječar',
        '16': 'Zlatibor',
        '17': 'Moravica',
        '18': 'Raška',
        '19': 'Rasina',
        '20': 'Nišava',
        '21': 'Toplica',
        '22': 'Pirot',
        '23': 'Jablanica',
        '24': 'Pčinja',
        '25': 'Kosovo',
        '26': 'Peć',
        '27': 'Prizren',
        '28': 'Kosovska Mitrovica',
        '29': 'Kosovo-Pomoravlje',
    },
    'SC': {
        '01': 'Anse aux Pins',
        '02': 'Anse Boileau',
        '03': 'Anse Etoile',
        '04': 'Au Cap',
        '05': 'Anse Royale',
        '06': 'Baie Lazare',
        '07': 'Baie Sainte Anne',
        '08': 'Beau Vallon',
        '09': 'Bel Air',
        '10': 'Bel Ombre',
        '11': 'Cascade',
        '12': 'Glacis',
        '13': 'Grand’Anse Mahe',
        '14': 'Grand’Anse Praslin',
        '15': 'La Digue and Inner Islands',
        '16': 'English River (Mont Fleuri older name?)',
        '17': 'Mont Buxton',
        '18': 'Plaisance',
        '19': 'Pointe La Rue',
        '20': 'Port Glaud',
        '21': 'Roche Caïman',
        '22': 'Saint Louis',
        '23': 'Takamaka',
    },
    'SL': {
        'E': 'Eastern Province',
        'N': 'Northern Province',
        'NW': 'North Western Province',
        'S': 'Southern Province',
        'W': 'Western Area',
    },
    'SG': {
        'S': 'Singapore',
    },
    'SX': {
        'SM': 'Sint Maarten (Dutch part)',
    },
    'SK': {
        'BC': 'Banskobystrický kraj',
        'BL': 'Bratislavský kraj',
        'KI': 'Košický kraj',
        'NI': 'Nitriansky kraj',
        'PV': 'Prešovský kraj',
        'TC': 'Trenčiansky kraj',
        'TA': 'Trnavský kraj',
        'ZI': 'Žilinský kraj',
    },
    'SI': {
        '001': 'Ajdovščina, Goriška (older references may differ)',
        '002': 'Beltinci, Pomurska',
    },
    'SB': {
        'CE': 'Central',
        'CH': 'Choiseul',
        'GC': 'Guadalcanal',
        'HO': 'Honiara (capital territory)',
        'IS': 'Isabel',
        'MK': 'Makira-Ulawa',
        'ML': 'Malaita',
        'RB': 'Rennell and Bellona',
        'TE': 'Temotu',
        'WE': 'Western',
    },
    'SO': {
        'AW': 'Awdal',
        'BK': 'Bakool',
        'BN': 'Banaadir (Mogadishu)',
        'BR': 'Bari',
        'BY': 'Bay',
        'GA': 'Galguduud',
        'GE': 'Gedo',
        'HI': 'Hiiraan',
        'JD': 'Jubbada Dhexe (Middle Juba)',
        'JH': 'Jubbada Hoose (Lower Juba)',
        'MU': 'Mudug',
        'NU': 'Nugaal',
        'SA': 'Sanaag',
        'SD': 'Shabeellaha Dhexe (Middle Shabelle)',
        'SH': 'Shabeellaha Hoose (Lower Shabelle)',
        'SL': 'Sool',
        'TO': 'Togdheer',
        'WO': 'Woqooyi Galbeed',
    },
    'ZA': {
        'EC': 'Eastern Cape',
        'FS': 'Free State',
        'GT': 'Gauteng',
        'KZN': 'KwaZulu-Natal',
        'LP': 'Limpopo',
        'MP': 'Mpumalanga',
        'NC': 'Northern Cape',
        'NW': 'North West',
        'WC': 'Western Cape',
    },
    'GS': {
        'SG': 'South Georgia and the South Sandwich Islands',
    },
    'SS': {
        'BN': 'Northern Bahr el Ghazal',
        'BW': 'Western Bahr el Ghazal',
        'EC': 'Central Equatoria',
        'EE': 'Eastern Equatoria',
        'EW': 'Western Equatoria',
        'JG': 'Jonglei',
        'LK': 'Lakes',
        'NU': 'Upper Nile',
        'UY': 'Unity',
        'WR': 'Warrap',

    },
    'ES': {
        'AN': 'Andalucía',
        'AR': 'Aragón',
        'AS': 'Asturias (Principado de Asturias)',
        'IB': 'Islas Baleares',
        'CN': 'Canarias',
        'CB': 'Cantabria',
        'CL': 'Castilla y León',
        'CM': 'Castilla-La Mancha',
        'CT': 'Cataluña (Catalunya)',
        'EX': 'Extremadura',
        'GA': 'Galicia',
        'RI': 'La Rioja',
        'MA': 'Madrid (Comunidad de)',
        'MC': 'Murcia (Región de)',
        'NC': 'Navarra (Comunidad Foral de)',
        'PV': 'País Vasco (Euskadi)',
        'VC': 'Comunidad Valenciana',

        'CE': 'Ceuta',
        'ML': 'Melilla',
    },
    'LK': {
        '1': 'Western',
        '2': 'Central',
        '3': 'Southern',
        '4': 'Northern',
        '5': 'Eastern',
        '6': 'North Western',
        '7': 'North Central',
        '8': 'Uva',
        '9': 'Sabaragamuwa',
    },
    'SD': {
        'DC': 'Central Darfur',
        'DE': 'East Darfur',
        'DN': 'North Darfur',
        'DS': 'South Darfur',
        'DW': 'West Darfur',
        'GD': 'Gedaref (Al Qadarif)',
        'GZ': 'Gezira (Al Jazirah)',
        'KA': 'Kassala',
        'KN': 'Khartoum (Al Kharṭūm)',
        'KS': 'North Kordofan (Shamāl Kurdufān)',
        'KW': 'West Kordofan (Gharb Kurdufān)',
        'NB': 'Blue Nile (An Nīl al Azraq)',
        'NO': 'Northern',
        'NR': 'River Nile (An Nīl)',
        'NW': 'White Nile (An Nīl al Abyaḍ)',
        'RS': 'Red Sea (Al Baḥr al Aḥmar)',
        'SI': 'Sennar (Sinnār)',
        'SK': 'South Kordofan (Janūb Kurdufān)',
    },
    'SR': {
        'BR': 'Brokopondo',
        'CM': 'Commewijne',
        'CR': 'Coronie',
        'MA': 'Marowijne',
        'NI': 'Nickerie',
        'PR': 'Para',
        'PM': 'Paramaribo',
        'SA': 'Saramacca',
        'SI': 'Sipaliwini',
        'WA': 'Wanica',
    },
    'SJ': {
        'S': 'Svalbard and Jan Mayen',
    },
    'SE': {
        'AB': 'Stockholms län',
        'AC': 'Västerbottens län',
        'BD': 'Norrbottens län',
        'C': 'Uppsala län',
        'D': 'Södermanlands län',
        'E': 'Östergötlands län',
        'F': 'Jönköpings län',
        'G': 'Kronobergs län',
        'H': 'Kalmar län',
        'I': 'Gotlands län',
        'K': 'Blekinge län',
        'M': 'Skåne län',
        'N': 'Hallands län',
        'O': 'Västra Götalands län',
        'S': 'Värmlands län',
        'T': 'Örebro län',
        'U': 'Västmanlands län',
        'W': 'Dalarnas län',
        'X': 'Gävleborgs län',
        'Y': 'Västernorrlands län',
        'Z': 'Jämtlands län',
    },
    'CH': {
        'AG': 'Aargau',
        'AI': 'Appenzell Innerrhoden',
        'AR': 'Appenzell Ausserrhoden',
        'BE': 'Bern / Berne',
        'BL': 'Basel-Landschaft',
        'BS': 'Basel-Stadt',
        'FR': 'Fribourg',
        'GE': 'Genève',
        'GL': 'Glarus',
        'GR': 'Graubünden / Grisons',
        'JU': 'Jura',
        'LU': 'Luzern',
        'NE': 'Neuchâtel',
        'NW': 'Nidwalden',
        'OW': 'Obwalden',
        'SG': 'Sankt Gallen',
        'SH': 'Schaffhausen',
        'SO': 'Solothurn',
        'SZ': 'Schwyz',
        'TG': 'Thurgau',
        'TI': 'Ticino',
        'UR': 'Uri',
        'VD': 'Vaud',
        'VS': 'Valais / Wallis',
        'ZG': 'Zug',
        'ZH': 'Zürich',
    },
    'TW': {
        'CHA': 'Changhua',
        'CYQ': 'Chiayi County',
        'CYI': 'Chiayi City',
        'HSQ': 'Hsinchu County',
        'HSZ': 'Hsinchu City',
        'HUA': 'Hualien',
        'ILA': 'Yilan',
        'KEE': 'Keelung',
        'KHH': 'Kaohsiung',
        'MIA': 'Miaoli',
        'NAN': 'Nantou',
        'PEN': 'Penghu',
        'PIF': 'Pingtung',
        'TAO': 'Taoyuan',
        'TNN': 'Tainan',
        'TPE': 'Taipei',
        'TTT': 'Taitung',
        'TXG': 'Taichung',
        'YUN': 'Yunlin',
    },
    'TJ': {
        'GB': 'Gorno-Badakhshan (Kuhistoni Badakhshon)',
        'KT': 'Khatlon',
        'SU': 'Sughd',
        'DU': 'Dushanbe (capital)',
        'RA': 'Districts of Republican Subordination (various districts)',
    },
    'TZ': {
        '01': 'Arusha',
        '02': 'Dar es Salaam',
        '03': 'Dodoma',
        '04': 'Iringa',
        '05': 'Kagera',
        '06': 'Kaskazini Pemba',
        '07': 'Kaskazini Unguja',
        '08': 'Kigoma',
        '09': 'Kilimanjaro',
        '10': 'Lindi',
        '11': 'Mara',
        '12': 'Mbeya',
        '13': 'Mjini Magharibi',
        '14': 'Morogoro',
        '15': 'Mtwara',
        '16': 'Mwanza',
        '17': 'Pwani (Coast)',
        '18': 'Rukwa',
        '19': 'Ruvuma',
        '20': 'Shinyanga',
        '21': 'Singida',
        '22': 'Tabora',
        '23': 'Tanga',
        '24': 'Manyara',
        '25': 'Geita',
        '26': 'Katavi',
        '27': 'Njombe',
        '28': 'Simiyu',
        '29': 'Songwe',
        '30': 'Kusini Pemba',
        '31': 'Kusini Unguja',
    },
    'TH': {
        '10': 'Bangkok (Krung Thep Maha Nakhon)',
        '11': 'Samut Prakan',
        '12': 'Nonthaburi',
        '13': 'Pathum Thani',
        '14': 'Phra Nakhon Si Ayutthaya',
        '15': 'Ang Thong',
    },
    'TL': {
        'AL': 'Aileu',
        'AN': 'Ainaro',
        'BA': 'Baucau',
        'BO': 'Bobonaro',
        'CO': 'Cova Lima',
        'DI': 'Dili',
        'ER': 'Ermera',
        'LA': 'Lautém',
        'LI': 'Liquiçá',
        'MF': 'Manufahi',
        'MT': 'Manatuto',
        'OE': 'Oecusse (special region)',
        'VI': 'Viqueque',

    },
    'TG': {
        'C': 'Centrale',
        'K': 'Kara',
        'M': 'Maritime',
        'P': 'Plateaux',
        'S': 'Savanes',
    },
    'TK': {
        'T': 'Tokelau',
    },
    'TO': {
        'T': 'Tonga',
    },
    'TT': {
        'ARI': 'Arima (Borough)',
        'CHA': 'Chaguanas (Borough)',
        'CTT': 'Couva–Tabaquite–Talparo (Region)',
        'DMN': 'Diego Martin (Region)',
        'PED': 'Penal–Debe (Region)',
        'POS': 'Port of Spain (City)',
        'PRT': 'Princes Town (Region)',
        'PTF': 'Point Fortin (Borough)',
        'RCM': 'Rio Claro–Mayaro (Region)',
        'SFO': 'San Fernando (City)',
        'SGE': 'Sangre Grande (Region)',
        'SIP': 'Siparia (Region)',
        'TOB': 'Tobago (Ward)',
        'TUP': 'Tunapuna–Piarco (Region)',
    },
    'TN': {
        '11': 'Tunis',
        '12': 'L’Ariana',
        '13': 'Ben Arous',
        '14': 'La Manouba',
        '21': 'Nabeul',
        '22': 'Zaghouan',
        '23': 'Bizerte',
        '31': 'Béja',
        '32': 'Jendouba',
        '33': 'Le Kef',
        '34': 'Siliana',
        '41': 'Kairouan',
        '42': 'Kasserine',
        '43': 'Sidi Bouzid',
        '51': 'Sousse',
        '52': 'Monastir',
        '53': 'Mahdia',
        '61': 'Sfax',
        '71': 'Gafsa',
        '72': 'Tozeur',
        '73': 'Kébili',
        '81': 'Gabès',
        '82': 'Médnine',
        '83': 'Tataouine',
    },
    'TR': {
        '01': 'Adana',
        '02': 'Adıyaman',
        '03': 'Afyonkarahisar',
        '04': 'Ağrı',
        '05': 'Amasya',
    },
    'TM': {
        'A': 'Ahal',
        'B': 'Balkan',
        'D': 'Daşoguz',
        'L': 'Lebap',
        'M': 'Mary',
        'S': 'Aşgabat (capital city, sometimes “Ashgabat”)',
    },
    'TC': {
        'T': 'Turks and Caicos Islands',
    },
    'TV': {
        'T': 'Tuvalu',
    },
    'UG': {
        'C': 'Central Region',
        'E': 'Eastern Region',
        'N': 'Northern Region',
        'W': 'Western Region',

    },
    'UA': {
        '71': 'Cherkaska oblast',
        '74': 'Chernihivska oblast',
        '77': 'Chernivetska oblast',
        '12': 'Dnipropetrovska oblast',
        '14': 'Donetska oblast (partly disputed)',
        '26': 'Ivano-Frankivska oblast',
        '63': 'Kharkivska oblast',
        '65': 'Khersonska oblast (partly disputed)',
        '68': 'Khmelnytska oblast',
        '35': 'Kirovohradska oblast',
        '30': 'Kyiv (special status city)',
        '32': 'Kyivska oblast',
        '09': 'Luhanska oblast (partly disputed)',
        '46': 'Lvivska oblast',
        '48': 'Mykolaivska oblast',
        '51': 'Odeska oblast',
        '53': 'Poltavska oblast',
        '43': 'Respublika Krym (Crimea, disputed)',
        '56': 'Rivnenska oblast',
        '59': 'Sumska oblast',
        '61': 'Ternopilska oblast',
        '05': 'Vinnytska oblast',
        '07': 'Volynska oblast',
        '21': 'Zakarpatska oblast',
        '23': 'Zaporizka oblast',
        '18': 'Zhytomyrska oblast',
    },
    'AE': {
        'AJ': 'ʻAjmān',
        'AZ': 'Abū Z̧aby (Abu Dhabi)',
        'DU': 'Dubayy (Dubai)',
        'FU': 'Al Fujayrah',
        'RK': 'Ra’s al Khaymah',
        'SH': 'Ash Shāriqah (Sharjah)',
        'UQ': 'Umm al Qaywayn',
    },
    'GB': {
        'EAE': 'East of England',
        'EMD': 'East Midlands',
        'GLN': 'Greater London',
        'NET': 'North East',
        'NWM': 'North West',
        'SE': 'South East',
        'SW': 'South West',
        'WM': 'West Midlands',
        'YHU': 'Yorkshire and the Humber',
        'SCT': 'Scotland',
        'WLS': 'Wales',
        'NIR': 'Northern Ireland'
    },
    'UM': {
        'US': 'United States Minor Outlying Islands',
    },
    'US': {
        'AL': 'Alabama',
        'AK': 'Alaska',
        'AZ': 'Arizona',
        'AR': 'Arkansas',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'HI': 'Hawaii',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'IA': 'Iowa',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'ME': 'Maine',
        'MD': 'Maryland',
        'MA': 'Massachusetts',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MS': 'Mississippi',
        'MO': 'Missouri',
        'MT': 'Montana',
        'NE': 'Nebraska',
        'NV': 'Nevada',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NY': 'New York',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VT': 'Vermont',
        'VA': 'Virginia',
        'WA': 'Washington',
        'WV': 'West Virginia',
        'WI': 'Wisconsin',
        'WY': 'Wyoming',
    },
    'UY': {
        'AR': 'Artigas',
        'CA': 'Canelones',
        'CL': 'Cerro Largo',
        'CO': 'Colonia',
        'DU': 'Durazno',
        'FD': 'Florida',
        'FS': 'Flores',
        'LA': 'Lavalleja',
        'MA': 'Maldonado',
        'MO': 'Montevideo',
        'PA': 'Paysandú',
        'RN': 'Río Negro',
        'RO': 'Rocha',
        'RV': 'Rivera',
        'SA': 'Salto',
        'SJ': 'San José',
        'SO': 'Soriano',
        'TA': 'Tacuarembó',
        'TT': 'Treinta y Tres',
    },
    'UZ': {
        'AN': 'Andijon',
        'BU': 'Buxoro',
        'FA': 'Farg‘ona',
        'JI': 'Jizzax',
        'KH': 'Xorazm',
        'NG': 'Namangan',
        'NW': 'Navoiy',
        'QA': 'Qashqadaryo',
        'QR': 'Qoraqalpog‘iston (Karakalpakstan, autonomous republic)',
        'SA': 'Samarqand',
        'SI': 'Sirdaryo',
        'SU': 'Surxondaryo',
        'TK': 'Toshkent (region)',
        'TO': 'Toshkent (city)',
    },
    'VU': {
        'VU': 'Vanuatu',
    },
    'VE': {
        'A': 'Caracas (Distrito Capital)',
        'B': 'Anzoátegui',
        'C': 'Apure',
        'D': 'Aragua',
        'E': 'Barinas',
        'F': 'Bolívar',
        'G': 'Carabobo',
        'H': 'Cojedes',
        'I': 'Falcón',
        'J': 'Guárico',
        'K': 'Lara',
        'L': 'Mérida',
        'M': 'Miranda',
        'N': 'Monagas',
        'O': 'Nueva Esparta',
        'P': 'Portuguesa',
        'R': 'Sucre',
        'S': 'Táchira',
        'T': 'Trujillo',
        'U': 'Yaracuy',
        'V': 'Zulia',
        'W': 'Dependencias Federales (Federal Dependencies)',
        'X': 'Vargas (La Guaira)',
        'Y': 'Delta Amacuro',
        'Z': 'Amazonas',
    },
    'VN': {
        '01': 'Lai Châu',
        '02': 'Lào Cai',
        '03': 'Hà Giang',
        '04': 'Cao Bằng',
        '05': 'Sơn La',
    },
    // TODO add
    'WF': {
        '': 'Wallis and Futuna'
    },
    'VI': {
        '': 'Wallis and Futuna'
    },
    'VG': {
        '': 'Wallis and Futuna'
    },
    'EH': {
        '': 'Wallis and Futuna'
    },
    // end oftodo
    'YE': {
        'AB': 'Abyan',
        'AD': "'Adan (Aden)",
        'AM': "‘Amrān",
        'BA': 'Al Bayḑā’',
        'DA': 'Ad Dāli‘',
        'DH': 'Dhamār',
        'HD': 'Ḥaḑramawt',
        'HJ': 'Ḥajjah',
        'HU': 'Al Ḩudaydah',
        'IB': 'Ibb',
        'JA': 'Al Jawf',
        'LA': 'Laḥij',
        'MA': 'Ma’rib',
        'MR': 'Al Mahrah',
        'MW': 'Al Maḩwīt',
        'RA': 'Raymah',
        'SA': 'Amānat al ‘Āşimah (Sanaa Municipality)',
        'SD': 'Şāʻdah',
        'SH': 'Shabwah',
        'SN': 'Sana’a (the surrounding governorate)',
        'SU': 'Socotra (Soqatra) - *sometimes part of Ḥaḑramawt or a separate area?',
        'TA': 'Tāʻizz',
    },
    'ZM': {
        '01': 'Western',
        '02': 'Central',
        '03': 'Eastern',
        '04': 'Luapula',
        '05': 'Northern',
        '06': 'North-Western',
        '07': 'Southern',
        '08': 'Copperbelt',
        '09': 'Lusaka',
        '10': 'Muchinga',
    },
    'ZW': {
        'BU': 'Bulawayo (city)',
        'HA': 'Harare (city)',
        'MA': 'Manicaland',
        'MC': 'Mashonaland Central',
        'ME': 'Mashonaland East',
        'MH': 'Mashonaland West',
        'MI': 'Midlands',
        'MN': 'Matabeleland North',
        'MS': 'Matabeleland South',
        'MV': 'Masvingo',
    },
}


type CountryKey = keyof typeof COUNTRY;
type State = typeof STATE_PROVINCE[keyof typeof STATE_PROVINCE];
type StateKey = KeysOfUnion<State>;


export type {StateKey, CountryKey};
export {COUNTRY, STATE_PROVINCE};